### ISSUE TITLE
Cannot run example and example2

### ISSUE THREAD

**Issue by josera21** [ppizarror/pygame-menu#1]
When I trie to run the examples is show me an error that cannot import the module Menu, especific in the line 19 from the  __init__.py file

**Comment by ppizarror** [comment]
Hola, qué versión de python tienes? Y qué sistema operativo, quizás no estoy manejando bien los path de la librería

**Comment by josera21** [comment]
Hola, Python 3.6.2 en Linux Manjaro 17.0.4

**Comment by ppizarror** [comment]
Saqué una nueva versión 1.7 (la puedes ver en [last-releases](https://github.com/ppizarror/pygame-menu/releases/latest)), actualmente funciona en:
- Python 2.7.13
- Python 3.6.3

Ambos probados en Windows 10 (c16299) y Linux Ubuntu 17.10.

**Comment by josera21** [comment]
Muchas gracias funciona muy bien, solo tuve problemas con la fuente 8bit en Linux mint 18.2.

**Comment by ppizarror** [comment]
Puedes usar nuevas fuentes también, no entiendo como funciona la administración de fuentes entre diversos sitemas operativos.

**Comment by josera21** [comment]
Gracias, la usare para hacer el menu de un simulador de partidos de futbol usando hilos con python, para un proyecto en la universidad, creo que con PyGame me ira mejor que con Qt.
