### ISSUE TITLE
Utility file for common methods

### ISSUE THREAD

**Issue by eforgacs** [ppizarror/pygame-menu#103]
Is there a file designated for methods that are common among multiple files? For instance, if there is a method that is exactly the same method in both menu.py and widget.py, and we wanted to refactor it into a different, common "utilities" file, does that file exist? I'm happy to make one if it doesn't already exist.

**Comment by ppizarror** [comment]
Nop, there's no `utils.py` file. Anyway removing duplicated code can improve testing and further refactoring. So go ahead! Maybe that'll be a nice addition 🤔

**Comment by eforgacs** [comment]
Okay, I'll do that. Thanks!
