### ISSUE TITLE
Improve mouse handling

### ISSUE THREAD

**Issue by arpruss** [ppizarror/pygame-menu#109]
Typical OSes handle mouse selection as follows:
- on mouse down, the widget is highlighted
- on mouse up, the widget function is executed, but only if it is the same widget as the mouse down happened in.

pygame-menu departs from this in two ways:
- there is no visual indication of mouse down
- on mouse up, the widget function is executed, even if the initial mousedown happened in a different widget.

The following change to the mouse event handling code makes the functioning a bit closer to standard:
```
                elif self._mouse and event.type == _pygame.MOUSEBUTTONDOWN:
                    for index in range(len(self._actual._option)):
                        widget = self._actual._option[index]
                        if widget.get_rect().collidepoint(*event.pos):
                            self._select(index)

                elif self._mouse and event.type == _pygame.MOUSEBUTTONUP:
                    widget = self._actual._option[self._actual._index]
                    if widget.get_rect().collidepoint(*event.pos):
                        widget.update(events)  # This option can change the current menu to a submenu
                        break_mainloop = True  # It is updated
                        break
```

**Comment by ppizarror** [comment]
Can you create a new pull request for this feature? So we can test the new behaviour 😄

**Comment by arpruss** [comment]
I'll see if I can. It's a bit of a nuisance, as my fork of it includes more changes (I needed to add multi-column functionality).

**Comment by ppizarror** [comment]
> I'll see if I can. It's a bit of a nuisance, as my fork of it includes more changes (I needed to add multi-column functionality).

If you want you can push here the multi-column functionality once you finish it (or at least have something usable), #20
thanks!

**Comment by ppizarror** [comment]
#114 implements this feature. The change is subtle, but I think that's useful if the user regrets after clicking any widget...

**Comment by ppizarror** [comment]
> #114 implements this feature. The change is subtle, but I think that's useful if the user regrets after clicking any widget...

#115 now
