### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Virinas-code** [ppizarror/pygame-menu#118]
Hello,
I can't find the documentation.
Can you help me ?

**Comment by anxuae** [comment]
Hi @Virinas-code,

The documentation is the main page of the repo: https://github.com/ppizarror/pygame-menu
You can find also examples in https://github.com/ppizarror/pygame-menu/tree/master/pygameMenu/examples

BR

**Comment by ppizarror** [comment]
@anxuae do you know any platform to "convert" pydoc documentation of the project to a website?
I think that README can be usable for small projects, but as for now the document is quite large

**Comment by anxuae** [comment]
Yes, I think you are right.
Read The Docs could be a good candidate: https://readthedocs.org

**Comment by ppizarror** [comment]
It would be super nice if anyone can generate the docs for this project using that tool. I tried to use this, but eventually failed in an *epic* way.

**Comment by anxuae** [comment]
I will take a look

**Comment by ppizarror** [comment]
Added to v3

**Comment by ppizarror** [comment]
@anxuae how I can use make? can you add a simple `readme.txt` in docs/?

**Comment by anxuae** [comment]
pip install sphinx
cd docs
make html

**Comment by anxuae** [comment]
Yes I will had it

**Comment by anxuae** [comment]
What is the file `_config.yml` at the root?

**Comment by ppizarror** [comment]
> What is the file `_config.yml` at the root?

trash, it was used while using github pages

**Comment by eforgacs** [comment]
In a similar vein, the link https://ppizarror.com/pygame-menu/ within __init__.py gives a 404 error. Should it maybe just be https://github.com/ppizarror/pygame-menu for now until https://ppizarror.com/pygame-menu/ is working again?

**Comment by ppizarror** [comment]
> In a similar vein, the link https://ppizarror.com/pygame-menu/ within **init**.py gives a 404 error. Should it maybe just be https://github.com/ppizarror/pygame-menu for now until https://ppizarror.com/pygame-menu/ is working again?

Yeah my server dns are quite a mess. But as for v3 that website is no longer valid. Now we will use readthedocs instead. Any documentation help is appreciated, because many method doc must be extended for Sphinx format like examples

**Comment by anxuae** [comment]
Note:
All inherited members (for instance in Button, Label, ..) shall ne have docstring defined.
Like that, the docstring will be also inherited.
I will clean Class and Methods docstrings

**Comment by ppizarror** [comment]
@anxuae The license format why has changed? I know it says MIT but now github does not show "MIT" as license on the main page

**Comment by anxuae** [comment]
Maybe due to change in the extension, I push a PR soon

**Comment by ppizarror** [comment]
Why these docs are gone? My editor throws me some warnings

![image](https://user-images.githubusercontent.com/12925256/79033804-35afd400-7b7f-11ea-9f65-176c468d41a9.png)

**Comment by anxuae** [comment]
See #131 ,  this permits to have the documents inherited from Widget class. 
However I can check if there is an way to avoid those warning

**Comment by anxuae** [comment]
In order to make the documentation usable, and dealing with overwritten methods, I see 3 possibilities:

1. copy in the docstring the same documentation as the base class
2. add the link in the docstring to the base class method
3. live with warning and no docstrings in child classes

We have to make a choice

**Comment by ppizarror** [comment]
I prefer 3, also added a flag for pycharm, problem solved!

**Comment by ppizarror** [comment]
@anxuae two questions:

1) Why pypi package version was deleted from README? I think that's an interesting banner to display. Or it's because in some cases the readme would not match to the displayed version?
2) The readme updates automatically on each commit?

**Comment by anxuae** [comment]
> @anxuae two questions:
> 
> 1. Why pypi package version was deleted from README? I think that's an interesting banner to display. Or it's because in some cases the readme would not match to the displayed version?

Sorry, I forgot several badges. Re-add them see #146 

> 2. The readme updates automatically on each commit?

Documentation on Readthedocs is regenerated automatically after some commit.
The file `README.rst` is edited manually

**Comment by anxuae** [comment]
The `README.rst` is really minimalist, and is included in the documentation on readthedocs

**Comment by anxuae** [comment]
I have some issue on ReadTheDocs with the web hook responsible of scruting GitHub if new commits exists.
I think is because it is your repo, can you try to configure the web hook? I had you as collaborator: https://readthedocs.org/dashboard/pygame-menu/integrations

**Comment by ppizarror** [comment]
> I have some issue on ReadTheDocs with the web hook responsible of scruting GitHub if new commits exists.
> I think is because it is your repo, can you try to configure the web hook? I had you as collaborator: https://readthedocs.org/dashboard/pygame-menu/integrations

I'll take a look

**Comment by ppizarror** [comment]
Fixed!

**Comment by anxuae** [comment]
thanks!
this issue can be closed
