### ISSUE TITLE
Move runtime engine to another class

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#120]
This is a proposal that comes into my mind because the `Menu` class becomes bigger.
The `Menu` class currently implements 2 things:

- the rendering of the menu itself
- the runtime engine used to display and process events of the top level menu

It could be possible to move all methods relative to the runtime engine (`_main`, `mainloop`, `_close`, `_get_depth`, `_back`, `full_reset`, `_get_actual_index`, ...) in a `MainMenu` class. the `Menu` class will inherit from it.
Globally all methods dealing with `_actual`, `_prev` and `_top` attributes should be moved in it.

The files `mainmenu.py`, `menu.py` and `textmenu.py` could be moved in a dedicated package `pygameMenu/menu`.

**Comment by ppizarror** [comment]
Seems promising.. But I think as for now that textmenu is quite useless. It's basically the same as Menu but with an aditional option. See #121

**Comment by anxuae** [comment]
Ok, that is right.
