### ISSUE TITLE
Merge TextMenu into Menu

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#121]
Seeing the code, actually the `add_text()` method can be easily implemented in Menu class. So `TextMenu` seems useless.

`.add_text()` can be a simple instance of a new widget `TextWidget` that does not catch any input and cannot be selected. This solution englobes all the menus into a single and simple global Menu class.

**Comment by anxuae** [comment]
The library  [textwrap](https://docs.python.org/3.1/library/textwrap.html) from the standard library could be use for text wrapping.

Better to avoid `widget` world in the name of the new widget to keep same naming philosophy has the other ones. Just call it `Text` or `Label`.
