### ISSUE TITLE
Use DirtySprites and improve performances

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#123]
To avoid CPU time consumption and have better performances on embedded devices (raspberry-pi), it could be good to avoid redraw the entire surface of the menu each time.

Pygame have basic classes to improve performances : `DirtySprite` and `LayeredDirty` which could be used in `pygame-menu`. See for instance: http://n0nick.github.io/blog/2012/06/03/quick-dirty-using-pygames-dirtysprite-layered

This does not imply to break everything, the current architecture can fit to this philosophy with minor changes: dirty flag in `Widget` class and redraw if `dirty=True`.

**Comment by ppizarror** [comment]
The idea is similar to #41?
Can you test this feature?

**Comment by anxuae** [comment]
Yes this is something like that but much more systematic.
In fact, the idea is to avoid to redraw all the menu, but redraw  only part of the screen that as changed since last frame. This avoid flipping all the pixels of the screen at each frame.
