### ISSUE TITLE
draw_region_x=0 overflow

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#126]
Strange behavior, when `draw_region_x=0` and `widget_alignment=locals.ALIGN_LEFT`, I expect that all widgets are on the left border.

However there is an overflow:

<img width="787" alt="align" src="https://user-images.githubusercontent.com/25277953/78810554-cabc9c80-79c8-11ea-83bd-a3a5d44b7c79.png">

**Comment by anxuae** [comment]
By the way, the use of these 2 options are little bit confusing: when I change widget_alignment to left, center or right, I expect that widgets are on the left, on center or one the right.

draw_region_x should be an offset?

**Comment by ppizarror** [comment]
> By the way, the use of these 2 options are little bit confusing: when I change widget_alignment to left, center or right, I expect that widgets are on the left, on center or one the right.
> 
> draw_region_x should be an offset?

Exactly. As same as draw_region_y.
Maybe, the parameters should be renamed to offset_x and offset_y in pixels and not as percentage. Because the width and height of the menu is in terms of px too. Using percentage is difficult to normalize and less precise

**Comment by ppizarror** [comment]
Also, font size, title font size, selected option inflate are in px. So this is the only parameter that require the "offset" as a percentage

**Comment by ppizarror** [comment]
Added to version 3

**Comment by anxuae** [comment]
Completely agree with you

**Comment by ppizarror** [comment]
Solved in #128
