### ISSUE TITLE
Remove config file

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#129]
If only are used by `Menu` class I think this file is redundant, also no one user can edit this file if library is downloaded by pip.

**Comment by ppizarror** [comment]
@anxuae what do you think?

**Comment by anxuae** [comment]
Right, the file `config.py` can not easily be edited (root acmes required).
I think that default values can just be hard coded in the kwargs of class and methods (even if it is a little bit redundant for some of ones)

**Comment by ppizarror** [comment]
#132
