### ISSUE TITLE
Make Menu running as other GUI elements

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#134]
To be consistent with any other widgets, GUI elements:

- the `Menu._main` should be rename to `Menu.update`
- the `Menu.draw` should take `surface` as argument
- the `Menu.mainloop` should take the `surface`, and `bgfun` arguments (remove them from `Menu` constructor)
- the `_dopause` attribute can be trashed

This is to ease the use of the menu, with less parameters in the `Menu` constructor.
But only a proposition, of course ;-). It's imply lots of changes.

Thus 2 scenario for the end user:

**1. Let's `pygame-menu` do the event loop:**

```python

def draw_background():
    ...

mymenu = Menu(...)

mymenu.mainloop(surface, bgfun=draw_background)
```

**2. User's application manage the event loop:**

```python

def draw_background():
    ...

mymenu = Menu(...)

While True:
    draw_background()

    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            exit()

    mymenu.update(events)

    mymenu.draw(surface)

    pygame.display.update()
```

**Comment by ppizarror** [comment]
I like this approach. Its elegant and offers 2 approaches instead of 1. The actual behaviour of menu is similar to 1.

**Comment by ppizarror** [comment]
While I'm coding it, `bgfun` must be callable, if not the menu background can not be rendered and the drawing glitches

**Comment by anxuae** [comment]
Yes, callable can be check in `mainloop` method.
However, we can let the user choose if it pass a bgfun parameter. If not, we will not redraw the background.

I thing that the call to this method should be done in the `draw()` one.

**Comment by ppizarror** [comment]
See #135

**Comment by ppizarror** [comment]
The changes to be compatible are minimal, just mainloop requires surface and bgfun, nothing more else. Also the second approach is done by `game_selector.py` example in `play_function()`

**Comment by anxuae** [comment]
Looks good for me

**Comment by ppizarror** [comment]
I had change quite a bit this approach, as timer_example did not work. Please see comments in #135

**Comment by ppizarror** [comment]
Merged #135, the last PR was way too large. Let's discuss some other changes here, any suggestion please make a PR 😄

**Comment by ppizarror** [comment]
#138 introduced updated status to the menu

**Comment by anxuae** [comment]
So much work done in one day! You're a killer ;)

**Comment by anxuae** [comment]
Some changes to discuss: #145

**Comment by ppizarror** [comment]
> So much work done in one day! You're a killer ;)

The quarantine is killing me jahjajaja

**Comment by ppizarror** [comment]
> Some changes to discuss: #145

Yes. Any color suggestion? I liked the blue pallete on the icon you made, but also the red/green color from some examples...

**Comment by anxuae** [comment]
Yes we can have something similar to the icon

**Comment by anxuae** [comment]
<img width="415" alt="first-color-choice" src="https://user-images.githubusercontent.com/25277953/79076473-b6dfa600-7cfa-11ea-9264-13553193989f.png">

**Comment by anxuae** [comment]
<img width="412" alt="second-color-choice" src="https://user-images.githubusercontent.com/25277953/79076541-3c635600-7cfb-11ea-97bd-b71d675f2596.png">

**Comment by ppizarror** [comment]
What if we introduce a new "Theme" class. Theme sets background color, widget color, highlight color and title color....

**Comment by ppizarror** [comment]
These two themes you made can be "blue", "i dont know what name can be", etc.

**Comment by anxuae** [comment]
Yes, it make me think to CSS style style sheet: https://www.w3schools.com/CSS/css_howto.asp

However for a quick menu, make a new object is not really quick. We can keep the menu parameters like this and add a new method `set_stylesheet()`

**Comment by ppizarror** [comment]
> Yes, it make me think to CSS style style sheet: https://www.w3schools.com/CSS/css_howto.asp
> 
> However for a quick menu, make a new object is not really quick. We can keep the menu parameters like this and add a new method `set_stylesheet()`

But what if for a quick menu

from pygameMenu.themes import BlueTheme

Menu(theme=BlueTheme)

By default Menu can be build with GrayTheme as it's more formal

**Comment by ppizarror** [comment]
Also, during execution time Menu the may change with `menu.set_theme(epic)`. Obviously this method will be called by the constructor

**Comment by ppizarror** [comment]
This improves the Menu removing many current options, 4-5 defining colors. Scrollbar color, shadow color, etc

**Comment by anxuae** [comment]
Ha yes, if we provide several themes.
Ok for a new module `pygameMenu.themes`!

**Comment by anxuae** [comment]
Maybe we can name Theme attributes same names as CSS.
Signification will be more understandable for people that have web notions.

**Comment by anxuae** [comment]
Update Theme screenshots :))

**Comment by ppizarror** [comment]
I like the new colors, amazing!

**Comment by ppizarror** [comment]
@anxuae are you working on the new theme class? Or it's future work?
I had an big idea, introduce a new object "Background". Background can be a color or an image. If it's an image the menu (and widgets) an be filled with an image repated or not (stretched), etc.

Now I'm working on an Image class, this will be used by Background and ImageWidget

**Comment by anxuae** [comment]
Yes, it could be cool to add background image (however I don't think a specific class is required).
I will integrate it in the Theme class.

I close this issue because topic has changed, see #162
