### ISSUE TITLE
Menu triggers event after releasing scrollbar

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#139]
See gif. The menu event handler catches an event after the user releases the scrollbar.

![epic](https://user-images.githubusercontent.com/12925256/79057048-c8f21380-7c2a-11ea-80ee-3ca72d4f511b.gif)

**Comment by ppizarror** [comment]
@anxuae

**Comment by anxuae** [comment]
I'm on it

**Comment by anxuae** [comment]
see PR #154
