### ISSUE TITLE
Add a scrollable menu

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#15]
That would be interesting, some ideas i have:
render the entire menu as an image, then clip the menu from a certain "**y**" coordinate to "min(**y**+*Hy*. *maxY*)" (where *Hy* height of the menu, *maxY* maximum menu rendered height).

Using some kind of y-overflow slider then that "**y**" coordinate can be changed 🤔

**Comment by anxuae** [comment]
I found this old repo with some examples of scroll panel: https://code.google.com/archive/p/ezscroll/source/default/source

**Comment by anxuae** [comment]
I will try to work on this issue

**Comment by ppizarror** [comment]
> I will try to work on this issue

epic. I'll try to work on the color plugin

**Comment by anxuae** [comment]
See PR.

Note that the structure of surfaces as fundamentally changed. The widgets are now drawn on a specific surface `_widgets_surface`. All the positions of the widgets are related to the origin of this surface.

<img width="750" alt="menu_surfaces" src="https://user-images.githubusercontent.com/25277953/78678774-b35ab200-78e9-11ea-9020-da08cad37853.png">

**Comment by anxuae** [comment]
Please test it and give me feedback.

Another point is the management of column, see `examples/scroll_menu.py` in the sub menu.
Currently column position try to fit the menu width, this behavior shall be modified to expand whatever the menu width if `force_fit_text=False`.

But need some help on it to understand management of column and `column_weights`

**Comment by anxuae** [comment]
Still have a bug in the text selection using the mouse when TextInput is scrolled

**Comment by ppizarror** [comment]
> Still have a bug in the text selection using the mouse when TextInput is scrolled

This has been fixed?

**Comment by anxuae** [comment]
Yes, this issue is fully solved
