### ISSUE TITLE
Make themes for menus

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#162]
Create a new module `pygameMenu.themes.py` to manage themes for menu:

```python
from pygameMenu.themes import BlueTheme
Menu(theme=BlueTheme)
```

Gray Theme (default)

<img width="409" alt="gray-theme" src="https://user-images.githubusercontent.com/25277953/79079024-bc45ec00-7d0c-11ea-8b97-e6a70040f39e.png">

Blue Theme

<img width="411" alt="blue-theme" src="https://user-images.githubusercontent.com/25277953/79079102-51e17b80-7d0d-11ea-9dab-69a278a2dfc8.png">

Green Theme

<img width="412" alt="second-color-choice" src="https://user-images.githubusercontent.com/25277953/79076541-3c635600-7cfb-11ea-97bd-b71d675f2596.png">

Solarized Theme

<img width="410" alt="solarized-theme" src="https://user-images.githubusercontent.com/25277953/79078947-1abe9a80-7d0c-11ea-8961-63b063a76caa.png">

**Comment by anxuae** [comment]
The concept is:

 - each menu has a defined theme
 - All widgets should have the attributes which are present available via Theme set to `None` by default.
 - When adding a widget, parameters can be set to overwrite the theme values
 - When the widget is drawing: take the its parameter if `!=None` else call `self._menu.theme.<param>`

**Comment by anxuae** [comment]
What do you think about this?

**Comment by ppizarror** [comment]
From `Menu` class, currently widgets once added call for "widget_default_xxx". That would be accesible through theme property. Also added selection to the theme

**Comment by ppizarror** [comment]
See #163, I used theme class in Menu, added a .copy() method for avoiding having the same instance of any theme in multiple menus (that could be dangerous)

**Comment by anxuae** [comment]
The doc is up to date.

See some comments on PR #163 .

**Comment by eforgacs** [comment]
I'd like to start working on the LeftArrow class, but I don't know where to begin. Can one of you guys point me in the right direction?

**Comment by ppizarror** [comment]
> I'd like to start working on the LeftArrow class, but I don't know where to begin. Can one of you guys point me in the right direction?

I'm working on a guide!

**Comment by ppizarror** [comment]
@eforgacs See https://github.com/ppizarror/pygame-menu/blob/master/pygameMenu/widgets/README.md

Any improvement on the README is appreciated, Hope it helps!

**Comment by anxuae** [comment]
Proposal to integrate it to the official documentation, see #167

**Comment by ppizarror** [comment]
> I'd like to start working on the LeftArrow class, but I don't know where to begin. Can one of you guys point me in the right direction?

https://pygame-menu.readthedocs.io/en/master/_source/advanced.html#create-a-selection-effect

**Comment by eforgacs** [comment]
> > I'd like to start working on the LeftArrow class, but I don't know where to begin. Can one of you guys point me in the right direction?
> 
> https://pygame-menu.readthedocs.io/en/master/_source/advanced.html#create-a-selection-effect

Thanks! This looks like it will help a lot. I'll give it a try!

**Comment by ppizarror** [comment]
Think this PR is done 😄
