### ISSUE TITLE
Blinking arrow

### ISSUE THREAD

**Issue by eforgacs** [ppizarror/pygame-menu#179]
Now that we have the arrows working, another functionality I'd like to add is to make the arrows blink, if so desired by the user. Here's my end goal:

![Blinking arrow](https://i.imgur.com/54URbEA.gif)

**Comment by ppizarror** [comment]
That can be easily implemented as follows:
- Add a blink_ms=0 in constructor of lef and right selections

Constructor should have the following attributes:
```
self._clock = pygame.time.Clock() 
self._blink_ms = 0
self._blink_time = 0
self._blink_status = True
```

If the blinking is 0 then this feature is disabled (the arrow will not blink), otherwise, in .draw() method update blink time with the tick time (how many ms have passed from the last drawing call).

```
draw()
   self._blink_time+=self._clock.get_time()
```

if the blinking time is greater than the limit, switch `self._blink_status`.

```
if self._blink_ms != 0 and self._blink_time>self._blink_ms:
    self._blink_status = not self._blink_status
```

Finally, draw only if `self._blink_status` is True

**Comment by ppizarror** [comment]
If you want to implement this, for refactoring please create a ArrowSelection that will be implemented in left and right arrows.

arrowselection class will handle this feature (and future too...). And it will be called in super().draw()

Also, let's wait for #180 as this introduces many core changes

**Comment by eforgacs** [comment]
> If you want to implement this, for refactoring please create a ArrowSelection that will be implemented in left and right arrows.
> 
> arrowselection class will handle this feature (and future too...). And it will be called in super().draw()
> 
> Also, let's wait for #180 as this introduces many core changes

Okay! Sounds good. I'll wait for #180 before working on this one. Thanks for the info! :)

**Comment by ppizarror** [comment]
#180 merged!

**Comment by eforgacs** [comment]
> #180 merged!

Nice! Starting on the blinking arrow now.

**Comment by eforgacs** [comment]
> If you want to implement this, for refactoring please create a ArrowSelection that will be implemented in left and right arrows.
> 
> arrowselection class will handle this feature (and future too...). And it will be called in super().draw()

To clarify, do we want ArrowSelection to be the parent class from which RightArrowSelection inherits? 

And if so, would it be located in pygame_menu\widgets\selection?

**Comment by ppizarror** [comment]
> > If you want to implement this, for refactoring please create a ArrowSelection that will be implemented in left and right arrows.
> > arrowselection class will handle this feature (and future too...). And it will be called in super().draw()
> 
> To clarify, do we want ArrowSelection to be the parent class from which RightArrowSelection inherits?
> 
> And if so, would it be located in pygame_menu\widgets\selection?

yes!! exactly, because its not a feature that will share among all widgets

**Comment by eforgacs** [comment]
Having a weird issue when I add the `self._clock = pygame.time.Clock()` line:

```
Traceback (most recent call last):
  File "C:/Users/eddie/PycharmProjects/pygame-menu/pygame_menu/examples/game_selector.py", line 298, in <module>
    main()
  File "C:/Users/eddie/PycharmProjects/pygame-menu/pygame_menu/examples/game_selector.py", line 209, in main
    submenu_theme = pygame_menu.themes.THEME_DEFAULT.copy()
  File "../..\pygame_menu\themes.py", line 262, in copy
    return copy.deepcopy(self)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python38-32\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'Clock' object
```

Any ideas?

**Comment by ppizarror** [comment]
Ops, maybe .copy() Theme tries to copy `self._clock = pygame.time.Clock()` object and it's not copiable.

What if you create a constant `SELECTOR_CLOCK=pygame.time.Clock()` in the Selection class you did. This object will not be copied every time Theme tries to copy widget_selection_effect object.

**Comment by eforgacs** [comment]
> Ooops, maybe `Theme.copy()` tries to copy `self._clock = pygame.time.Clock()` object and it's not copiable.
> 
> What if you create a constant `SELECTOR_CLOCK=pygame.time.Clock()` in the Selection class you did. This object will not be copied every time Theme tries to copy widget_selection_effect object.

That runs, but `self._blink_time` is always 0 when I do that.

**Comment by eforgacs** [comment]
Okay, committed in #183. Let me know what you think.

**Comment by ppizarror** [comment]
I've done some refactors. Now I think it's ready for merge!

**Comment by ppizarror** [comment]
Merged. I need to fix some things. Please any other feature or issue create a new PR. You decide if this issue will still opened

**Comment by eforgacs** [comment]
> Merged. I need to fix some things. Please any other feature or issue create a new PR. You decide if this issue will still opened

Thanks for refactoring/merging! If there's a few minor fixes that need to be made, that's fine, but for our purposes, as long as there's an arrow, and it blinks, I'd say we can call this one done. Anything else would be beyond the scope of "blinking arrow," I think. I'll close it out!

**Comment by ppizarror** [comment]
Added to docs!

https://pygame-menu.readthedocs.io/en/master/_source/advanced_selection.html
