### ISSUE TITLE
How to close a menu when an item is selected?

### ISSUE THREAD

**Issue by wrybread** [ppizarror/pygame-menu#19]
I can't figure out how to close a menu when an item is selected. If I understand the docs correctly, running menu1.disable() should close menu1, but that's not working for me.

In the attached sample keyboard button 1 makes menu1 appear, and selecting an item *should* make it disappear since I'm setting menu1.disable(), but nothing happens and the menu stays visible. Interestingly, pressing ESC closes the menu (which is what I want to happen when an item is selected).

And for testing, keyboard button 2 makes menu2 appear.

Any tips on making the menus disappear after an item is selected?

[sample.zip](https://github.com/ppizarror/pygame-menu/files/2409705/sample.zip)

**Comment by wrybread** [comment]
I seem to have fixed the issue by changing mainloop() to the following. Is that a correct fix for this?

[code]
    def mainloop(self, events):
        """
        Main function of Menu, draw, etc.

        :param events: Menu events
        :return: None
        """
        assert isinstance(self._actual, Menu)

        if self.is_disabled():
            return
        if self._actual._dopause:
            while True:

                #%%% added this line to fix menus not closing (with this addition it closes when calling disable())
                if not self.is_enabled(): return 

                if self._main():
                    return
        else:
            self._main(events)
[/code]

Attached is the changed file.

[menu.zip](https://github.com/ppizarror/pygame-menu/files/2409895/menu.zip)

**Comment by ppizarror** [comment]
hi!

I found it's not a problem about the library, is just when you press return into that select you start *item_selected* function (line 47) ... but it eventually ends (because there's any mainloop there) so it returns to the main *while True* (line 109).

If you change:

```
# triggered when menu item selected
def item_selected(arg):
    # print "item selected %s" % arg

    menu1.disable()  # should close menu1? But isn't...
    menu2.disable()  # should close menu2? But isn't...
    # print "here, menu1: %s" % menu1.is_enabled()
    # print "here, menu2: %s" % menu2.is_enabled()

    # menu2.reset(100)
    # menu2.reset(1)

    while True: # the real while True of your app....
        clock.tick(60)
        surface.fill((255, 0, 0))
        pygame.display.update()
        events = pygame.event.get()
        ....
```

You will be able to see a nice red color in the screen.
If you wish you can modify the documentation if something is not clear 🤔

**Comment by ppizarror** [comment]
here's the "fixed" file
[pygamesample_fix.zip](https://github.com/ppizarror/pygame-menu/files/2413166/pygamesample_fix.zip)

**Comment by wrybread** [comment]
Very interesting and thanks! And thanks for the response, I'm a huge fan of pygame-menu!

What's the advantage of that over simply exiting the menu (or not drawing it) when it's disabled?

**Comment by ppizarror** [comment]
i don't know really, somehow i realized that that was the best practice considering how pygame was made. I prefer to keep two different main loops: one for the menus and another for the MVC architectural pattern of your application.

Anywai you can have "all in one" main loop instruction, but what would be a mess considering all different events.

Maybe an advanced example of usage can be a project of mine (racing game [Ned-For-Spod](https://github.com/ppizarror/Ned-For-Spod)), there you have lot's of menus, pause-menu, results-menu, etc.

If you're interested you can write another example showing another architecture: ¿threads maybe?

**Comment by wrybread** [comment]
Adding the line as described in my second post above closes the menu neatly. I don't see a disadvantage, since the menu runs the loop anyway. Seems messy to introduce yet another loop on item selection. But maybe I'm missing something.

**Comment by ppizarror** [comment]
mmm yep, it seems confusing ... maybe you could create a function named "exit" so it disables the menu 🤔

**Comment by wrybread** [comment]
Personally I think just disabling the menu with menu1.disable() is a very intuitive way of closing it.
