### ISSUE TITLE
pygame-menu v3

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#191]
Added a pre-release of the library in https://github.com/ppizarror/pygame-menu/releases
I plan to release v3 to PyPI in 1st may.

Anything not covered in https://pygame-menu.readthedocs.io/en/master/_source/migration_guide.html please create a new PR or comment here

Thanks to @anxuae and @eforgacs

**Comment by eforgacs** [comment]
Thank you @ppizarror!

**Comment by anxuae** [comment]
I'm impatient to integrate it!

**Comment by zPaw** [comment]
Are the docs updated to version 3 or are they still for version 2? It isn't obvious looking through them.

**Comment by ppizarror** [comment]
> Are the docs updated to version 3 or are they still for version 2? It isn't obvious looking through them.

https://pygame-menu.readthedocs.io/en/master/ is for v3
https://github.com/ppizarror/pygame-menu/blob/v2/README.md is for v2

**Comment by zPaw** [comment]
> https://pygame-menu.readthedocs.io/en/master/ is for v3
https://github.com/ppizarror/pygame-menu/blob/v2/README.md is for v2

Thanks for the clarification!

**Comment by ppizarror** [comment]
> > https://pygame-menu.readthedocs.io/en/master/ is for v3
> > https://github.com/ppizarror/pygame-menu/blob/v2/README.md is for v2
> 
> Thanks for the clarification!

Added that to README

**Comment by ppizarror** [comment]
Finally uploaded to PyPI!! Closing this issue by now, thanks!!
