### ISSUE TITLE
title_offset TypeError when creating a custom theme

### ISSUE THREAD

**Issue by eforgacs** [ppizarror/pygame-menu#197]
When I create a custom theme, and use the title_offset kwarg to pass in a tuple of ints, I get the following `TypeError`:

`TypeError: isinstance() arg 2 must be a type or tuple of types`

I tried removing line 360 from themes.py:
`assert isinstance(value, others), msg`

And then it works. Is this also happening on your end?

**Comment by ppizarror** [comment]
I think this is related to this PR: https://github.com/ppizarror/pygame-menu/commit/bd5efcd92f99de8af66afde01a50facd77e8e098

I'll push a new version right now

**Comment by eforgacs** [comment]
Yep, that fixed it. Thanks!
