### ISSUE TITLE
missing menu.update() triggers additional event

### ISSUE THREAD

**Issue by smilefab** [ppizarror/pygame-menu#199]
Suppose i have the following main loop:

      while True:
            events = pygame.event.get()
            for event in events:
                if event.type == QUIT:
                    pygame.quit()
                    exit()
                elif event.type == KEYDOWN:
                    if event.key == K_ESCAPE:
                        main_menu.toggle()
            
            if main_menu.is_enabled():
                self.screen.fill((120, 120, 120))
                main_menu.update(events)
                main_menu.draw(self.screen)
            else:
                self.screen.fill((40, 0, 40))

            pygame.display.flip()

If i press the escape key while running the main loop, a pygame.KEYDOWN event gets triggered twice.  This enables the menu but closes it right after, so that the menu is never visible. Only if I call

       main_menu.update(events)

EVERY time I run the loop, the pygame.KEYDOWN event gets triggered like it's supposed to. The caveat of this is that the menu is controlled whilst running the application, which for example can cause the whole program to exit.

![Unbenannt](https://user-images.githubusercontent.com/57106872/82127960-871f3480-97b7-11ea-9ffd-fe73673d8251.PNG)

Here I printed out all the pygame events after pressing the escape button several times. Each time you can see two KEYDOWN events and one KEYUP event

**Comment by anxuae** [comment]
Hi @smilefab 

One solution it to not update the menu in the loop where K_ESCAPE was pressed. For instance:

```python
while True:
    events = pygame.event.get()
    toggle_menu = False
    for event in events:
        if event.type == pygame.QUIT:
            pygame.quit()
            exit()
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                main_menu.toggle()
                toggle_menu = True

    if not toggle_menu and main_menu.is_enabled():
        screen.fill((120, 120, 120))
        main_menu.update(events)
        main_menu.draw(screen)
    else:
        screen.fill((40, 0, 40))

    pygame.display.flip()
```

**Comment by smilefab** [comment]
I still don't quite understand why the `main_menu.update` would change the event list for the next loop. Your solution seems to work though.

If not change the implementation, maybe change this in the documentation and the timer_clock.py example?

**Comment by anxuae** [comment]
Yes, there is probably something to improve about that.

By the way, you are right, there is something wrong with events.
@ppizarror : It seems that the function `utils.check_key_pressed_valid` is generating sometimes wrong events.

**Comment by anxuae** [comment]
Hi @smilefab 

When the double event appears, does a `TextInput` widget was selected?

**Comment by ppizarror** [comment]
> Yes, there is probably something to improve about that.
> 
> By the way, you are right, there is something wrong with events.
> @ppizarror : It seems that the function `utils.check_key_pressed_valid` is generating sometimes duplicated events.

I know, this function exists because if user types too fast (or keeps a key pressed) somehow the events are executed even if the user released the key. Maybe this method is irrelevant considering the fact the events should only be evaluated on the single update instance

**Comment by smilefab** [comment]
@anxuae 
Absolutely! In Fact, only when a `TextInput` widget is selected, the bug appears. 
![test](https://user-images.githubusercontent.com/57106872/82182930-5f2def00-98e5-11ea-8b1b-6bb1e9c47170.gif)
Here you can see the behaviour. When another widget is selected, the menu works as expected.

**Comment by ppizarror** [comment]
I've found the issue. @anxuae 

See TextInput line 1663:

                event_key, event_unicode = key, self._keyrepeat_counters[key][1]
                try:
                    # noinspection PyArgumentList
                    pygame.event.post(pygame.event.Event(pygame.KEYDOWN,
                                                         key=event_key,
                                                         unicode=event_unicode)
                                      )
                except pygame.error:  # If the keys are too fast pygame can raise a Sound Exception
                    pass

If user keeps a key pressed for too long time menu raises a event. The bad news here is that if a user presses ESC this event is duplicated too.

I suggest change this feature introducing some kind of "inner events". Something like
input._events.append(pygame.event.Event(...). That event will be used exclusively on the next update().

If somehow the widget loses the context and there's more events to be applied just wipe the list.
_events can be a property of Widget core class.

**Comment by ppizarror** [comment]
> I've found the issue. @anxuae
> 
> See TextInput line 1663:
> 
> ```
>             event_key, event_unicode = key, self._keyrepeat_counters[key][1]
>             try:
>                 # noinspection PyArgumentList
>                 pygame.event.post(pygame.event.Event(pygame.KEYDOWN,
>                                                      key=event_key,
>                                                      unicode=event_unicode)
>                                   )
>             except pygame.error:  # If the keys are too fast pygame can raise a Sound Exception
>                 pass
> ```
> 
> If user keeps a key pressed for too long time menu raises an event. The bad news here is that if a user presses ESC this event is duplicated too, the same happens with BACK key (as this key can move through submenus).
> 
> I suggest change this feature introducing some kind of "inner events". Something like
> input._events.append(pygame.event.Event(...). That event will be used exclusively on the next update().
> 
> If somehow the widget loses the context and there's more events to be applied just wipe the list.
> _events can be a property of Widget core class.

**Comment by ppizarror** [comment]
> Yes, there is probably something to improve about that.
> 
> By the way, you are right, there is something wrong with events.
> @ppizarror : It seems that the function `utils.check_key_pressed_valid` is generating sometimes duplicated events.

I tested `utils.check_key_pressed_valid` and it's not generating duplicated events

**Comment by anxuae** [comment]
Hi everybody,

@ppizarror the `K_ESCAPE` and `K_BACKSPACE` should be added to the `TextInput._ignore_keys` dict and it should solve the issue.

However, you are right, we can increase the robustness by generate a custom event for the repeat case.

**Comment by ppizarror** [comment]
Hi. Added more `TextInput._ignore_keys` and using custom events approach this issue has been solved. See #201
