### ISSUE TITLE
Possible to have two columns?

### ISSUE THREAD

**Issue by wrybread** [ppizarror/pygame-menu#20]
Any idea what would be required to make it possible to have two columns of items in a menu? I see that there's a "left" and "right" direction, so maybe this was an intended feature?

I'm glad to help implement it.

**Comment by ppizarror** [comment]
i think it's possible, maybe a function named add_container(*args) that can contain any items, selectors, etc... so if container is drawn add (x,y) to all items within ...

Possible usage:

```python
# Returns some kind of menu object instance
container_left = main_menu.add_container(x='10%',y=50,float='left',max_width='50%'....)
container_left.add_selector(....)

container_right = main_menu.add_container(x='10%',y=50,float='right',max_width='50%'....)
```

max_width, float, x or y padding can be optional parameters of the container object.

"left" and "right" work with selectors, when you add a list of items and the user press "LEFT" or "RIGHT" button in order to change the value

**Comment by chrisjd20** [comment]
Is this a thing? I dont see it in the readme.

**Comment by ppizarror** [comment]
> Is this a thing? I dont see it in the readme.

It has not been implemented yet :cry:

**Comment by chrisjd20** [comment]
Would definitely be a nice feature if you can get used to it but this library kicks ass regardless - Great job man.

**Comment by ppizarror** [comment]
> Would definitely be a nice feature if you can get to it but this library kicks ass regardless - Great job man.

Any push request is appreciated, there's a lot of things to improve. Greetings! :smile:

**Comment by eforgacs** [comment]
Seconding @chrisjd20 's sentiment. Would love to see this feature! (This thread is the first result on Google for 'pygame menu with columns'). I'd be happy to contribute to working on it as well. Any ideas on where to begin?

**Comment by ppizarror** [comment]
To solve this problem I think in boxes like the grid engine in CSS.
The whole menu area can be the 100% in horizontal and vertical.

By default the menu contains an "box" with all the area. If two boxes are added (each one with 50% of the width) then the widgets belonging to each box are written based on the coordinates from the parent element, like

```
for each box in area:
     xi, yi = box.get_relative_coords()
     for each widget in box:
           widget.draw(xi+widget.posx, y+widget.posy)
```

The widget max width should be the width of the parent element.

To solve problems in alignment, maybe all boxes are appended at the left of the parent element. So if anyone wants a right menu, something like this can be done:

```
container = menu.create_container(width=100%, vertical=80%)
container.add_empty(width=50%)
rightcontainer = container.add_box(width=50%)

rightcontainer.add_button(....)
```

rightcontainer max width should be the 50% of the menu width in px. Then add_button should pass the max width to the widgets.

Anyway this solution is not easy at all, all widgets should be refactored. Also this solution must be compatible with alignment.

**Comment by ppizarror** [comment]
PD: Maybe something like

`menu.add_widget(container=rightcontainer)`

Is better and less confusing

**Comment by ppizarror** [comment]
#115 fixes this issue!

**Comment by eforgacs** [comment]
Awesome!!!! Thank you so much!

**Comment by ppizarror** [comment]
@eforgacs merged to master!

**Comment by eforgacs** [comment]
> @eforgacs merged to master!

Woo hoo!! This is great 😄 Thanks again for all the hard work!

**Comment by anxuae** [comment]
Working fine also for me.

Still a work to do for compatibility with scrolling menu: see #15
