### ISSUE TITLE
How to remove X from top right of menu?

### ISSUE THREAD

**Issue by Uskompuf** [ppizarror/pygame-menu#204]
Is it possible to remove the X in the top right of the menu, I had a look at theme options but couldn't see one.

**Comment by ppizarror** [comment]
Use back_box=False on Menu constructor.
https://pygame-menu.readthedocs.io/en/stable/_source/create_menu.html#pygame_menu.Menu

Anyway, I think this feature should be added to themes... @anxuae ?

**Comment by ppizarror** [comment]
Also, the description of the parameter in docs could be changed... New ideas are welcome

**Comment by ppizarror** [comment]
I suggest, "back_box" -> "back_close_header_button" ...

**Comment by anxuae** [comment]
> Anyway, I think this feature should be added to themes... @anxuae ?

I agree, it could be added.

> I suggest, "back_box" -> "back_close_header_button" ...

"menubar_close_button" ?

**Comment by ppizarror** [comment]
I agree!

**Comment by ppizarror** [comment]
Done! New version v3.1 will provide Theme.menu_close_button.  I used warnings for user prevention
