### ISSUE TITLE
Support input chinese?

### ISSUE THREAD

**Issue by lzlz000** [ppizarror/pygame-menu#207]
how can i use chinese input method to input chinese characters to  wiget text_input ,  like this:  
![image](https://user-images.githubusercontent.com/22382840/83738224-9858b400-a686-11ea-939d-627dbd6ba0d0.png)
it doesn't work

**Comment by ppizarror** [comment]
hi! can you provide an example source code in chinese. I'll try to test the chinese inputs to see if there's any issue.
What python and pygame version are you using?
Thanks.
