### ISSUE TITLE
Pygame Menu Background

### ISSUE THREAD

**Issue by katurkmen** [ppizarror/pygame-menu#209]
Hey there,
I have problem with putting background image behind the menu. I have read [issue](https://github.com/ppizarror/pygame-menu/issues/9) that you have resolved, however the link you sent is not working anymore. The main problem I am facing is image showing of nearly a second and it disappears. Here is [my code](https://paste.ubuntu.com/p/mGQyfvCbcR/).

Take care.

**Comment by ppizarror** [comment]
I'll add an example of image background. It works with BaseImage class or just using the normal image load with python.

**Comment by ppizarror** [comment]
![Captura](https://user-images.githubusercontent.com/12925256/85324956-cae11a00-b498-11ea-9b14-13d8bca71304.PNG)

**Comment by katurkmen** [comment]
Alright, thank you :)

**Comment by ppizarror** [comment]
Please see: https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/examples/other/image_background.py
Also, new version 3.1.2 is required. If there's any bug please open a new issue thread! Thanks
