### ISSUE TITLE
pygame-menu doesn't see font after compiling using pyinstaller

### ISSUE THREAD

**Issue by MrKris7100** [ppizarror/pygame-menu#212]
When i compile my app based on pygame and pygame-menu and run executable i got error about loading font:
`Traceback (most recent call last):
  File "Main.py", line 550, in <module>
    menus.append(pygame_menu.Menu(height, width, 'Title', theme=theme))
  File "site-packages\pygame_menu\menu.py", line 280, in __init__
  File "site-packages\pygame_menu\widgets\core\widget.py", line 548, in set_font
  File "site-packages\pygame_menu\font.py", line 118, in get_font
ValueError: system font "C:\Users\Krzychu\AppData\Local\Temp\_MEI37082\pygame_menu\resources\fonts\opensans_regular.ttf" unknown, use "yugothicmediumyugothicuiregular" instead
check system fonts with pygame.font.get_fonts() function
some examples: candara, microsoftjhengheimicrosoftjhengheiuilight, simsunextb
[8008] Failed to execute script Main`
Without compiling to executable works fine.

PS. System: windows 10

**Comment by ppizarror** [comment]
maybe you need to use another fonts, or the compilation must include the resource folder containing the fonts (pygame_menu/resources/fonts/). I don't know that are the flags requiered with pyinstaller

**Comment by kassenna** [comment]
copy the folder of pygame_menu do dist/name of program

**Comment by Tilmandel** [comment]
> copy the folder of pygame_menu do dist/name of program

this doesnt work in my case, as my exe is starting in user\AppData\Local\temp and for example there is no  resource folder  there
right now i eddited pygame_menu.font.py with 
__fontdir__ = path.join(path.dirname(path.abspath(__file__)), 'resources', 'fonts', '{0}')
if "Temp" in __fontdir__:
    __fontdir__ = r"Path to resources" but this is hardcoded and will not work with changing env, later on i will sitdown and change that for dynamic default sys font

**Comment by ppizarror** [comment]
> > copy the folder of pygame_menu do dist/name of program
> 
> this doesnt work in my case, as my exe is starting in user\AppData\Local\temp and for example there is no resource folder there
> right now i eddited pygame_menu.font.py with
> **fontdir** = path.join(path.dirname(path.abspath(**file**)), 'resources', 'fonts', '{0}')
> if "Temp" in **fontdir**:
> **fontdir** = r"Path to resources" but this is hardcoded and will not work with changing env, later on i will sitdown and change that for dynamic default sys font
> 
> **edit**:
> You can:
> pyinstaller --onefile --add-binary="source;dest" your_script_name.py
> But this will eventually make your file bigger and bigger if you add many binaries

Pygame menu now supports pyinstaller #264, now just execute your pyinstaller and it will automatically add all resources to the binary without any worries. That's because menu triggers a pyinstaller hook that incorporates all resources to the binary distribution.

**Comment by Tilmandel** [comment]
Thanks for your respond, good to hear that it was fixed, but sadly in my
company we dont have that version of pygame_menu, so still i need to solve
this for now i have added binaries in build process with --add-binary flag

Kind Regards
Jaroslaw Woloszyn

czw., 4 lut 2021, 14:10 użytkownik Pablo Pizarro R. <
notifications@github.com> napisał:

**Comment by MrKris7100** [comment]
Good to hear that, thanks for fix :)
