### ISSUE TITLE
Encoding utf8

### ISSUE THREAD

**Issue by cesar-tdf** [ppizarror/pygame-menu#215]
Hola, cuando intento ingresar botones con textos en utf-8 en python2.7, encuentro problemas del tipo 'ascii' codec. En python 3 no encuentro inconvenientes.  

Error 'ascii' codec
 ```
 File "/home/carrasin/.local/lib/python2.7/site-packages/pygame_menu/menu.py", line 363, in add_button
    title = str(title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 20: ordinal not in range(128)

```
la linea que produce el error es 

```
self.menu.add_button(u'Ejercicio 1 Evaluación', self.ComenzarEjercicio1)
```

la manera de escribir el texto correctamente lo pude solucionar pasando el texto a latin1
```
self.menu.add_button(u'Ejercicio 1 Evaluación'.encode('latin1'), self.ComenzarEjercicio1)
```

Por lo que pude ver, el problema radica en que la funcion Font.render diferencia entre  textos unicode y char strings, asumiendo que los char strings solo pueden ser LATIN1.

https://www.pygame.org/docs/ref/font.html#pygame.font.Font.render

>Both Unicode and char (byte) strings are accepted. For Unicode strings only UCS-2 characters ('u0001' to 'uFFFF') are recognized. Anything greater raises a UnicodeError. For char strings a LATIN1 encoding is assumed.

No tengo tanta experiencia en Python pero al parecer la funcion str() varía entre ambas versiones. No sé si vale la pena aun mantener la compatibilidad con la versión 2.7. Pude comprobar que eliminado el uso de la funcion str y la validaciones de tipo         assert isinstance(text, str) el texto se muestra correctamente ingresando el texto en utf8.  

La solución es un compromiso entre validar el ingreso de string de las funciones y mantener la compatibilidad con python 2.7. Si decides mantener el código como está, por lo menos dejo un ejemplo de cómo utilizar caracteres utf8.

Saludos y felicitaciones por la libreria es muy completa

**Comment by ppizarror** [comment]
La intención de eso era sólo transformar los números, ya que habían usuarios que pedían hacer cosas como add_button(0). Una solución sería hacer algo como

`if isinstance(title, (int,float)):
    title=str(title)
`

De esta manera se satisface el hecho de aceptar también números.

**Comment by cesar-tdf** [comment]
Ahh ahi esta el motivo del str(). S{i, eso solucionaría el problema de las asignaciones.Pero faltarian los isinstance (title , str) ya que en python 2 hace diferencia entre textos str y unicode. 

Para comparar ambos según encontré en SO la forma mas elegante de validar es con basestring y declarándola en python3 (ya que en python3 no existe basestring, todos los textos son utf8 y de tipo str)


 https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

De  la siguiente manera se puede seguir verificando si la variable es de tipo str o char string, en python2 o python3 
```
>>> s=u'hello'
>>> if not hasattr(__builtins__, "basestring"): basestring = (str, bytes)
... 
>>> isinstance(s, basestring)
True

```

**Comment by ppizarror** [comment]
He creado el pull request con los cambios sugeridos, estos afectan a todos los widgets y al menú (título, etc). Tuve que añadir si una comprobación estricta en los selectores ya que éstos usan el string.format(). y si no se hace encode tira estos errores como "'ascii' codec can't encode character u'\xf3' in position "

**Comment by ppizarror** [comment]
version 3.2.0 publicada y subida a pip, cerraré este thread. Si hay otros errores porfavor abrir otro issue. saludos
