### ISSUE TITLE
Problem with pygame_menu.events.BACK

### ISSUE THREAD

**Issue by slavakamrad** [ppizarror/pygame-menu#218]
Hello,

I have a problem with pygame_menu.events.BACK call. 
The game started, opened start menu, I'm click Settigs button, and opened start_settings_menu. Cool. But when I want to go to  start_menu, no way... Help please.
 
```
def open_start_settings_menu():
    start_settings_menu = pygame_menu.Menu(800, 830, game_name, theme=my_theme)
    start_settings_menu.add_button('Back', pygame_menu.events.BACK)
    start_settings_menu.mainloop(win)

def open_start_menu(start):
    start_menu = pygame_menu.Menu(800, 830, game_name, theme=my_theme)
    start_menu.add_button('Play', start)
    start_menu.add_button('Settings', open_start_settings_menu)
    start_menu.add_button('Quit', pygame_menu.events.EXIT)
    start_menu.mainloop(win)
```

**Comment by ppizarror** [comment]
Hi, The problem with your code is that when 'Back' is executed from start_settings_menu object, ¿how can python know that start_menu should continue? There's no clear connection between these two objects in your example.

One solution is to append settings_menu as an submenu of start_menu. That can be done adding a submenu as a button:

`
start_settings_menu = pygame_menu.Menu(800, 830, game_name, theme=my_theme)
start_settings_menu.add_button('Back', pygame_menu.events.BACK)

start_menu = pygame_menu.Menu(800, 830, game_name, theme=my_theme)
start_menu.add_button('Play', start)
start_menu.add_button('Settings', start_settings_menu)
start_menu.add_button('Quit', pygame_menu.events.EXIT)
start_menu.mainloop(win)
`

If the Play button is clicked, the current execution of the mainloop of the start menu is directed to settings_menu. If then, the user presses back, the event tells the original menu (start_menu) that the execution pointer should reset.

There's plenty of examples you can look from, I hope these can help you to see how to operate the menu in different conditions:
https://github.com/ppizarror/pygame-menu/tree/master/pygame_menu/examples

**Comment by slavakamrad** [comment]
It's work! Thank you so much!
