### ISSUE TITLE
Upload a version on PyPi

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#22]
Hi

Is it possible to build a version and upload it on PyPi to ease the deployment?
(or maybe it is already done, but I can't find it)

Thanks
anxuae

**Comment by ppizarror** [comment]
it's done: pip install pygame-menu

if you experience some issues please create a new issue
greetings!! 😄

**Comment by ppizarror** [comment]
also, if there's something that you wish to change (new features...) feel free to commit
