### ISSUE TITLE
Touchscreen support on menu with pygame 2+

### ISSUE THREAD

**Issue by werdeil** [ppizarror/pygame-menu#222]
Sorry if I have missed something but I can't manage to make the menu work with a touchscreen on pygame 2.

ISince pygame 2 and the switch to SDL2 the touchscreen support have evolved, we now have `FINGERxxxx` events (`FINGERDOWN`, `FINGERUP`, `FINGERMOTION`) and touch events are no longer considered as click events. I think this is the reason the touch on the menu are no longer working.

**Comment by ppizarror** [comment]
That could be an amazing addition, but I don't have any touch device that runs Windows 10 so I could not be able to test it. Do you have used these new events? Any PR is welcome :)

**Comment by ppizarror** [comment]
Pushed new version 3.3.2 along some other changes. Thanks!
