### ISSUE TITLE
How to properly add sub-menu?

### ISSUE THREAD

**Issue by wokalove** [ppizarror/pygame-menu#226]
Am I supposed to close old one and then open new one or just switch off between menus ?

Could you give me a proper example?

thank you in advance! :)

**Comment by ppizarror** [comment]
Hi, there's not a standard way to add sub-menus, it only relies on your project architecture. There's a couple of examples, including sub-menus as well, take a look, and if there's no evident example I'll create a new one 👍 
https://pygame-menu.readthedocs.io/en/latest/_source/gallery.html

**Comment by wokalove** [comment]
Thank you a lot! Your pygame-menu is really helpful and saved me some time while creating my little project on Object Oriented Programming classes.

Could you once more help me how to get return value from `add_text_input` ?

I have sth like:

`user_name = game_menu.add_text_input('First name: ', default='')`
`game_menu.add_button('Play',start_game,user_name)`

This passes a user_name to start_game function, but I don't know how to get user's input. 

Thank you for spending time on your library! Good job :)

**Comment by ppizarror** [comment]
you can use .get_value() method 😄 
https://pygame-menu.readthedocs.io/en/latest/_source/widgets_textinput.html#pygame_menu.widgets.TextInput.get_value

**Comment by wokalove** [comment]
Omg, so sorry, I must overlooked it hahah :D Thanks, it works xD

**Comment by ppizarror** [comment]
Maybe the method description is not the best... I may change it, any recommendation?

**Comment by wokalove** [comment]
Maybe practical examples of use? Not each method of course, because it would be pointless, but one will be enogh and clearly will say what we should do to get a result. I know that you have gallery examples, but they are full and more complex and looking for certain option is time consuming. But that is only my suggestion. This library is very helpful and that was really good idea to create sth like that :D Keep up with good work

**Comment by ppizarror** [comment]
Nice. I'll close this issue by now, if you have any suggestion or feature request feel free to create any pull request or new issue. Thanks!
