### ISSUE TITLE
selector widgets

### ISSUE THREAD

**Issue by RickyAsbury** [ppizarror/pygame-menu#227]
I'm having trouble with the selector and your documentation but I'm still having trouble. I'm hoping you can help me figure out what I'm doing wrong
[Adventures_of_Rick.zip](https://github.com/ppizarror/pygame-menu/files/5683423/Adventures_of_Rick.zip)
NOTE:the python file is inside

**Comment by ppizarror** [comment]
Have you seen the game selector example? https://pygame-menu.readthedocs.io/en/latest/_source/gallery.html There's a couple of examples in the repo, maybe one of them is similar to your project
