### ISSUE TITLE
Adding padding to a widget

### ISSUE THREAD

**Issue by Mysterken** [ppizarror/pygame-menu#229]
If I'm not mistaken, there's currently no way to add padding to a widget.
In my case it's a problem if I want the left and right border of each buttons to align:  

![Capture d’écran (182)](https://user-images.githubusercontent.com/16426148/102241028-cdc54080-3ef8-11eb-8f80-58ea80b5ecd7.png)

Would an implementation of an optional  widget_padding argument be possible?

**Comment by ppizarror** [comment]
Yep, it's entirely possible. I'll look for an implementation of widget_padding

**Comment by ppizarror** [comment]
Padding has been implemented. Some possible combinations:

```python
menu.add_button(0, pygame_menu.events.NONE, padding=25)
menu.add_button(0, pygame_menu.events.NONE, padding=(25, 50, 75, 100))
menu.add_button(0, pygame_menu.events.NONE, padding=(25, 50))
menu.add_button(0, pygame_menu.events.NONE, padding=(25, 75, 50))
```

This is entirely experimental. Some issues should be resolved but I need user feedback. I'll create a new version today, hope this resolves your issue

**Comment by ppizarror** [comment]
Padding rules are the same as CSS https://www.w3schools.com/css/css_padding.asp

**Comment by ppizarror** [comment]
I'll leave this issue opened for suggestions or further feedback after v340 is released

**Comment by ppizarror** [comment]
New version 3.4.0 released. If there's any feedback, suggestion or bug please create a new issue or a PR
