### ISSUE TITLE
Moving widgets vertically

### ISSUE THREAD

**Issue by AlcuZan** [ppizarror/pygame-menu#230]
Firstly I want to say, I love this module. ppizarror has even helped me via mail, he is a great guy.
Problem: 
- I have a combination of buttons, a selector and an image
- The menu is as big as the surface (1680x1060px)

The widgets appear in the center of the screen and I want to move them up slightly. That doesn't work.
Firstly, I choose a theme and make a copy of it: `theme = pygame_menu.themes.THEME_DARK.copy()`
Then I try to change the position of the widgets, using `theme.widget_offset`. This only works for the x axes, and only to the right side, because you can't enter negative values for the offset. Altering the second value of `theme.widget_offset` does nothing. It's supposed to move the widgets vertically, but that doesn't happen. Am I doing something wrong or is this bugged?

**Comment by ppizarror** [comment]
Can you provide a complete example to test this issue?

Maybe it can be an error ahaahah, At first glance I thought positions would be easy... but not when making a library

**Comment by AlcuZan** [comment]
Sure thing mate. First of all, you made it so that no negative values are allowed for `widget_offset`. So that makes it impossible to move the widgets to the left side or to the bottom, right? <br>
![grafik](https://user-images.githubusercontent.com/19841508/102724656-5edd5280-4311-11eb-9acf-57d68c20718c.png)


I'm taking your example `simple.py` here and will modify it a little bit to show the issue. Hope that's okay.
```python
import os
import pygame
import pygame_menu

pygame.init()
os.environ['SDL_VIDEO_CENTERED'] = '1'
surface = pygame.display.set_mode((1000, 600))


def set_difficulty(selected, value):
    """
    Set the difficulty of the game.
    """
    print('Set difficulty to {} ({})'.format(selected[0], value))


def start_the_game():
    """
    Function that starts a game. This is raised by the menu button,
    here menu can be disabled, etc.
    """
    print('Do the job here !')

theme = pygame_menu.themes.THEME_DARK.copy()
theme.widget_offset = (0, 0)

menu = pygame_menu.Menu(height=600,
                        width=1000,
                        theme=theme,
                        title='Welcome')

menu.add_text_input('Name: ', default='John Doe')
menu.add_selector('Difficulty: ', [('Hard', 1), ('Easy', 2)], onchange=set_difficulty)
menu.add_button('Play', start_the_game)
menu.add_button('Quit', pygame_menu.events.EXIT)

if __name__ == '__main__':
    menu.mainloop(surface)

```
The above code produces this:<br>
![grafik](https://user-images.githubusercontent.com/19841508/102724609-060dba00-4311-11eb-9bb6-de5931fdb76b.png)

Now when I try to move the widgets vertically by setting `theme.widget_offset` to `(0, 300)`:<br>
![grafik](https://user-images.githubusercontent.com/19841508/102724627-2fc6e100-4311-11eb-98c2-ebfcfb5b8708.png)

Looks exactly the same.

**Comment by AlcuZan** [comment]
Sure thing mate. First of all, you made it so that no negative values are allowed for `widget_offset`. So that makes it impossible to move the widgets to the left side or to the bottom, right? <br>
![grafik](https://user-images.githubusercontent.com/19841508/102724656-5edd5280-4311-11eb-9acf-57d68c20718c.png)


I'm taking your example `simple.py` here and will modify it a little bit to show the issue. Hope that's okay.
```python
import os
import pygame
import pygame_menu

pygame.init()
os.environ['SDL_VIDEO_CENTERED'] = '1'
surface = pygame.display.set_mode((1000, 600))


def set_difficulty(selected, value):
    """
    Set the difficulty of the game.
    """
    print('Set difficulty to {} ({})'.format(selected[0], value))


def start_the_game():
    """
    Function that starts a game. This is raised by the menu button,
    here menu can be disabled, etc.
    """
    print('Do the job here !')

theme = pygame_menu.themes.THEME_DARK.copy()
theme.widget_offset = (0, 0)

menu = pygame_menu.Menu(height=600,
                        width=1000,
                        theme=theme,
                        title='Welcome')

menu.add_text_input('Name: ', default='John Doe')
menu.add_selector('Difficulty: ', [('Hard', 1), ('Easy', 2)], onchange=set_difficulty)
menu.add_button('Play', start_the_game)
menu.add_button('Quit', pygame_menu.events.EXIT)

if __name__ == '__main__':
    menu.mainloop(surface)

```
The above code produces this:<br>
![grafik](https://user-images.githubusercontent.com/19841508/102724609-060dba00-4311-11eb-9bb6-de5931fdb76b.png)

Now when I try to move the widgets vertically by setting `theme.widget_offset` to `(0, 300)`:<br>
![grafik](https://user-images.githubusercontent.com/19841508/102724627-2fc6e100-4311-11eb-98c2-ebfcfb5b8708.png)

Looks exactly the same.

**Comment by ppizarror** [comment]
Hi, I found that you're using center_content=True, then widget_offset vertical position is "overridden".

The following code works as intended:
```python
import os
import pygame
import pygame_menu

pygame.init()
os.environ['SDL_VIDEO_CENTERED'] = '1'
surface = pygame.display.set_mode((1000, 600))


def set_difficulty(selected, value):
    """
    Set the difficulty of the game.
    """
    print('Set difficulty to {} ({})'.format(selected[0], value))


def start_the_game():
    """
    Function that starts a game. This is raised by the menu button,
    here menu can be disabled, etc.
    """
    print('Do the job here !')

theme = pygame_menu.themes.THEME_DARK.copy()
theme.widget_offset = (0, 300)

menu = pygame_menu.Menu(height=600,
                        width=1000,
                        theme=theme,
                        title='Welcome',
                        center_content=False)

menu.add_text_input('Name: ', default='John Doe')
menu.add_selector('Difficulty: ', [('Hard', 1), ('Easy', 2)], onchange=set_difficulty)
menu.add_button('Play', start_the_game)
menu.add_button('Quit', pygame_menu.events.EXIT)

if __name__ == '__main__':
    menu.mainloop(surface)
```

For avoiding this issue, if vertical offset is different than zero, and center_content is not False it will raise a warning

**Comment by ppizarror** [comment]
From now on, this message is displayed using your example:

```
menu.py:253: UserWarning: menu is vertically centered (center_content=True), but widget offset (from theme) is different than zero (300px). Auto-centering has been disabled
  warnings.warn(msg)
```

**Comment by AlcuZan** [comment]
Thanks, it works now! :)
