### ISSUE TITLE
Cannot install pygame-menu

### ISSUE THREAD

**Issue by RickyAsbury** [ppizarror/pygame-menu#231]
I'm having issues installing this on the raspberry-pi 4 Model B. it keeps giving me this Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iECkYk/pygame/
I was hoping you could help me resolve this error

**Comment by RickyAsbury** [comment]
it worked when I was using it on windows but I don't understand why it won't work for the Raspberry pi 4.

**Comment by ppizarror** [comment]
Hi! Sorry for responding too late, I'm on my semester finals and it's horrible.
This issue is related to #221, it's not a problem of the library itself, it's a problem of pygame. Try using a lower version (1.9.6), that should work and this library also supports pygame 1.9.6
