### ISSUE TITLE
off by one error in column calculation

### ISSUE THREAD

**Issue by arpruss** [ppizarror/pygame-menu#233]
In Menu._configure_widget(), the _col calculation has an off-by-one error. It should be `_col = int(len(self._widgets) // self._rows)` , because `len(self._widgets)` gives the number of previous widgets not counting this one. Currently, the first widget of each column got the _col value of the previous column, which threw off the width calculations.

**Comment by ppizarror** [comment]
New version 3.4.0 released, thanks!
