### ISSUE TITLE
Access all widgets in a menu

### ISSUE THREAD

**Issue by AlcuZan** [ppizarror/pygame-menu#237]
Currently it's not possible (without a warning) to iterate through all widgets in a menu, because `_widgets` is a private attribute in the class `Menu`. Adding a property fixes this problem:

```python
@property
def widgets(self):
return self._widgets
```
I guess this was done on purpose, but why? I'd like the option to access all widgets that my menu contains (e.g. to insert a widget at a specific place in the menu).

**Comment by ppizarror** [comment]
Hi, the problem to access this private array is that appending widgets without using its methods can break the Menu. If this list is modified, outside the class, the following variables should be changed too:

````python
self._index (if added in the same position as previous selected one), then the new widget should be selected too
self._widgets_surface
if self._center_content: self.center_content()
```

Maybe it could be possible to return the widgets of the menu, but only in a non-mutable object like a tuple:

````python
@property
def widgets(self):
     return tuple(self._widgets)
```

**Comment by ppizarror** [comment]
Anyway, the architecture of the library and new methods are entirely debatable. For me, a private method is more pythonic than accessing the private variables without asking first the object

**Comment by AlcuZan** [comment]
I see, thanks for the explanation. Maybe I am doing something wrong or there is another solution for my problem, that is absolutely possible. 

My use case is that I have a menu with a character selector:
![grafik](https://user-images.githubusercontent.com/19841508/103464166-df4c7c00-4d31-11eb-9006-85008bc67b4d.png)

Depending on which character is chosen, the portrait and the backstory of that character appear in the menu, while the portrait and backstory of the other character disappear and vice versa. So when I switch to the other character it looks like this:
![grafik](https://user-images.githubusercontent.com/19841508/103464218-4a964e00-4d32-11eb-8fbf-ce8af07a27f3.png)

To accomplish this, I iterate through the widgets in the menu when the selected item changes and delete every widget but the selector, then readding every widget that is needed for the current character (image and text) plus the two buttons. I need to delete everything but the selector to keep the widgets in the order that you can see in the screenshot. 

Is there any way to accomplish this when I don't want to access `self._widgets` of the `Menu` class? This is my current solution:
```python
removal_complete = False
        while not removal_complete:
            for widget in self.menu._widgets:
                # Removes all widgets that are not a Selector
                if not isinstance(widget, Selector):
                    self.menu.remove_widget(widget)
                if all(isinstance(w, Selector) for w in self.menu._widgets):
                    # The while loop stops when there is only the Selector left in the widgets list
                    removal_complete = True
```

**Comment by ppizarror** [comment]
What if you get the reference of the image and label widgets and change their contents? I'm working right now to provide more methods for modifying the Image widget, and I'll create a new example valid only for v3.4.0 that changes dynamically the widgets in the menu without removing them.

Also, menu will have a new method for getting the tuple of the widgets.... so users can modify them using indexes

**Comment by ppizarror** [comment]
New example in #238 shows dynamic widget update:

![example_other_dynamic_widgets](https://user-images.githubusercontent.com/12925256/103467527-ad85e600-4d2e-11eb-9ccf-109f2fc8321e.gif)

Several new methods were created:
- Image widget can be created from BaseImage object
- BaseImage offers method to change pixel colors from function, to_black_white and pick_channels
- This example is based on OOP style

**Comment by ppizarror** [comment]
Also added new methods .show() and .hide(). The new example, aside from modifying the widgets, toggle between two buttons as shown in the following image:

![example_other_dynamic_widget_update](https://user-images.githubusercontent.com/12925256/103470215-5132be80-4d4e-11eb-8d2a-26b44b445c7f.gif)

**Comment by AlcuZan** [comment]
Thank you, this looks exactly like the thing I need 👍

**Comment by AlcuZan** [comment]
Found another bug because I didn't realize I shouldn't use the class `Button` separately.
I created a class called `MyButton`, which inherits your Button class. Works fine per se, but when I try to use the new functions `hide()` or `show()`, this happens:<br>
![grafik](https://user-images.githubusercontent.com/19841508/103478331-31d77800-4dc6-11eb-9e62-a75f524ea95f.png)

This is because in my `MyButton` class, I did not set any font for the buttons. I understand that the way to add buttons is via the `add_button` method, but I grouped all my buttons in a class and didn't find it convenient to always pass the menu instance to the button functions:

```python
class MyButton(Button):
    """Extends basic Button class"""

    def __init__(self, text: ButtonTexts, action):
        super().__init__(text.value.text, text.value.button_id)
        self.action = action

class Buttons:
    """Class for all buttons"""
    @staticmethod
    def button_confirm(action):
        """Creates confirm button with given action (usually opening a new menu)."""
        return MyButton(ButtonTexts.CONFIRM, action)
```
I suppose deleting `MyButton` and instead doing this would fix the problem:
```python
@staticmethod
    def button_confirm(menu, action):
        return menu.add_button(ButtonTexts.CONFIRM, action)
```

**Comment by ppizarror** [comment]
That's an interesting edge case usage. I've pathed the bug in #239.

**Comment by AlcuZan** [comment]
Got another problem. I need to pass the information about the character a player has chosen to the next menu (see my screenshot above, the "Bestätigen" button opens the next menu, which then has information about the character the player has chosen as varibale `self.p1_char`). I do this by calling `add_button`, which contains the menu instance for the next menu as `action`: `self.menu.add_button(MenuAttributeSelectionP1(self.window, self.p1_char).menu)`

`self.p1_char` updates whenever the selector changes. It contains information about the chosen character like the name, img etc. The next menu needs this information so the game later knows which player chose which character and what the attributes of these characters are (they get added in the next menu). How do I inform the button about the update? When I change the selector from "Elias" to "Klaus", the next menu needs to know that player 1 has chosen "Klaus", but currently it always thinks that player 1 has chosen "Elias", because that is the default that I define in the `init` of the menu class. The button gets no knowledge that the player changes the character. How do I accomplish this without deleting the "Bestätigen" button and readding it? `update_callback` doesn't accept menu instances...

**Comment by ppizarror** [comment]
Do you mean letting the button to change the menu it points to? It can be added...; the only change it has to be made is to remove the current menu pointer from the parent submenus.

Let me know if I did understand you correctly.

**Comment by AlcuZan** [comment]
The menu it changes to is the same (MenuAttributeSelectionP1), but the information `self.p1_char` depends on the selected item (the class MenuAttributeSelectionP1 expects the attribute `p1_char`). Each of my menus has its own class because if I put all submenus in one class I'd lose overview pretty quickly.

**Comment by ppizarror** [comment]
What if you store a reference to all widgets to be changed. And update them on demand by user interaction. Something similar to the example I did (https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/examples/other/dynamic_widget_update.py). Something like

```python
self.mutable_button = self.menu.add_button(MenuAttributeSelectionP1(self.window, self.p1_char).menu)

def on_change_selector(id):.
    self.mutable_button.set_title(PLAYERS_CHAR[id])
```

I don't see another design pattern to change this. There's no way the button can know if "p1_char" has changed because you pass it as a value rather than a reference; it's just a string.

Anyway, I see a possible solution: Create some kind of ``add_listener(listener_function)`` and ``fire_listeners()`` to widget class. That functions receive the same widget as parameter. For example:

```python:
def update_title(self,widget):
    widget.set_title(self.p1_char)

def your_menu_assemble():
    ...
    btn = self.menu.add_button(MenuAttributeSelectionP1(self.window, self.p1_char).menu)
    btn.add_listener(update_title)
    ...

def your_selector_on_change():
    self.menu.fire_widget_listeners(recursive=True/False) -> Eventually this will reach your button, and update_title would be executed
```

This design pattern is totally debatable.  Can it resolve your issue?

**Comment by AlcuZan** [comment]
Sorry, I should've specified. `p1_char` and `p2_char` are no strings, they are `Character` objects that hold the name, image, backstory and attributes (intelligence, charisma, dexterity etc.) of a character. So `set_title` wouldn't work because it only changes the text of the widget, which is not what I need. Right now the solution that works is as follows: I have a module called `public` where I instantiate both characters: 

```python
p1_char: Character = Characters.ELIAS
p2_char: Character = Characters.KLAUS
```
`Characters` is a class that stores every possible `Character`.
Then in the module `menus.py`, which handles all menus, I call and modify these attributes using `public.p1_char` and `public.p2_char` instead of using `self.p1_char` etc. in every menu class. I guess it's not very pythonic, but it works.

**Comment by ppizarror** [comment]
I'll close this issue as the new version has been published, and it's way too large.
https://github.com/ppizarror/pygame-menu/releases/tag/3.4.0

If you have any suggestions, feel free to create a new issue. A PR is welcome too.
