### ISSUE TITLE
Change widget_background_color to cover up to the border

### ISSUE THREAD

**Issue by Mysterken** [ppizarror/pygame-menu#242]
Using the new widget_padding we can see it work as intended and create a padding around the widget:
```
title_screenTheme.widget_padding = 10
```
![Capture d’écran (152)](https://user-images.githubusercontent.com/16426148/103523605-66a60680-4e7c-11eb-83c0-4a1daaffeb15.png)

The issue is that the black background of the widget do not expand, following the [CSS Box Model](https://www.w3schools.com/css/css_boxmodel.asp) it seems that `widget_background_color` only cover the "Content" part of the box, shouldn't it expand up to the "Border" of the box ?
In my opinion it makes more sense since in CSS `background-color` [does expand up to the "Border"](https://www.w3schools.com/css/tryit.asp?filename=trycss_boxmodel).

In my case of `add_button`:
```
title_screen.add_button('Start new game', self.start_new_game)
title_screen.add_button('Load Save', self.LoadSave)
title_screen.add_button('Option', self.OptionMenu.Menu)
title_screen.add_button('About', self.About)
title_screen.add_button('Exit', self.ExitGame)
```
I think the only visible "Content" should be the title of the button.

**Comment by ppizarror** [comment]
It was my mistake. I forgot to include background. Now it's patched :)

**Comment by Mysterken** [comment]
Oh, nice !
Thanks for your work !

**Comment by ppizarror** [comment]
Now widget position and sizing can be updated during execution time. New callbacks added during draw and update

![example_other_dynamic_widget_update](https://user-images.githubusercontent.com/12925256/103594880-aa2e5e00-4ed8-11eb-887f-dbf2ef798fca.gif)

**Comment by ppizarror** [comment]
The example was done using the following code:

```

def animate_quit_button(widget, menu):
      t = widget.get_attribute('t', default=math.pi)
      t += menu.get_clock().get_time() * 0.001
      widget.set_attribute('t', t)
      widget.set_padding(10 * (1 + math.sin(t)))  # Oscillating padding
      new_color = (int(125 * (1 + math.sin(t))), 0, 0)
      widget.set_background_color(new_color, None)
      widget.update_font({'background_color': new_color})

button.add_draw_callback(animate_quit_button)
```

**Comment by ppizarror** [comment]
See https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/examples/other/dynamic_widget_update.py
