### ISSUE TITLE
widget_background_color apply twice

### ISSUE THREAD

**Issue by Mysterken** [ppizarror/pygame-menu#246]
With the latest version 3.4.3 `widget_background_color` seems to cover both around the text and around the border which cause a layered effect.

See this:
![Capture d’écran (160)](https://user-images.githubusercontent.com/16426148/103669503-b2d67100-4f78-11eb-8a75-115ca9686900.png)

**Comment by ppizarror** [comment]
The background color you defined has an alpha channel right (transparency). I can confirm this issue too, I've only tested opaque colors. I'll take a look at it

**Comment by Mysterken** [comment]
Yep, I'm using an alpha channel in this case.

**Comment by ppizarror** [comment]
Fixed. Incorporated them also in a current example

![image](https://user-images.githubusercontent.com/12925256/103699879-5f692080-4f82-11eb-8b33-9e17b4e085b0.png)

**Comment by ppizarror** [comment]
I'll publish a new version. Feel free to point me out any bug or issue, or even a new PR if you have some API suggestions
