### ISSUE TITLE
Stop Menu

### ISSUE THREAD

**Issue by R2D2Hud** [ppizarror/pygame-menu#248]
How can I Make the menu quit?

**Comment by ppizarror** [comment]
Hello. I don't know your menu architecture. But you can add a button with a exit or close event. For example

```
menu = Menu(...)
menu.add_button('Quit', pygame_menu.events.CLOSE)
```

**Comment by BackMountainDevil** [comment]
> How can I Make the menu quit?
see [Doc](https://pygame-menu.readthedocs.io/en/3.4.4/), add a quit btn
```bash
menu.add_button('Quit', pygame_menu.events.EXIT)
menu.mainloop(surface)
```
