### ISSUE TITLE
Allow Path object as image_path for BaseImage class

### ISSUE THREAD

**Issue by AlcuZan** [ppizarror/pygame-menu#261]
**Is your feature request related to a problem? Please describe.**
I like working with pathlib, but BaseImage only accepts a string as image_path, so I always have to put `as_posix` behind my image paths.

**Describe the solution you'd like**
Allow `image_path` to be a string OR a pathlib.Path

**Comment by ppizarror** [comment]
Can you provide a minimal example of pathlib?
