### ISSUE TITLE
Beforeload event

### ISSUE THREAD

**Issue by SANGERA2** [ppizarror/pygame-menu#275]
I would LOVE a beforeload event (or maybe there is a way to jump from one menu another in code and still remember parent/sub menus). 

Basically I have a main menu that has submemus and I want to be able to run code before the submemu is run that calls clear on the sub menu, pulls data from a file and uses that to populate it with labels. This needs to happen every time the submemu is loaded, not when the program is first run. I looked through every example very carefully and couldn't find how to do this. 

I love the simple, way I can pass in the name of a menu to a button and it loads that and allows me to return to the main menu easily, but I want to run code begore that menu is loaded (maybe a beforeload parameter when you add a button if you're passing in a menu object instead of a function callback). I tried to write code to disable the main menu and enable the submemu and then run the submemu mainloop method, but then I lost the ability to go back to the main menu.

Thanks.

**Comment by ppizarror** [comment]
Hi! That is a nice addition to the Menu. As the v4 of the menu is coming soon that feature will be added to that version.

If I understood you clearly, ``beforeload`` callback would execute before "opening" a new menu state? (obviously the beforeload event of the new opened menu)

For example:

```python
menu = Menu()
menu2 = Menu(beforeload=lambda: print('hiii'))
btn = menu.add_button(menu2)
btn.apply() # This opens menu 2, and before loading prints "hiii"
```

**Comment by SANGERA2** [comment]
Thanks very much. There are two options really: firstly it could be added to the menu class (as in your example) so whenever a submenu is switched to or someone goes back to the main menu it runs code. A second option would be to add it to the button class and whenever a button is given a form to load, it could run code a function before that.

I can see cases where both options would be useful.

**Comment by ppizarror** [comment]
I'll add ``onbeforeload`` as the button should not modify the behavior of menu stats (rather than firing some callbacks). Also, if user resets or opens the menu these callbacks should be fired too independently of the button.

This will be added soon to the ``master`` branch (v4).
