### ISSUE TITLE
Clear without reset (or remove_all_widgets) 

### ISSUE THREAD

**Issue by SANGERA2** [ppizarror/pygame-menu#276]
I saw from your code that the clear function calls full-reset first. I assume this wipes out any submenu navigation history. Possibly the existing clear function could be modified to not call full-reset first and a new function created called clear_and_reset or a new function created called remove_all_widgets

Anyway, in my use case, I'd like to be able to remove all the widgets from a menu or submenu and regenerate them when navigating between menus and still keep the menu history so that I can stay on the current menu without being kicked back to the root menu. 

I assume this is what is happening when I call clear on a menu anyway. I created a submenu that had a single button on it that called the clear on itself and filled it with labels (it was my ugly workaround for not being able to run code before the menu was created). When this function ran it generated the menu correctly, but it also kicked me back to the main menu.

**Comment by ppizarror** [comment]
Hi. I think that, as full_reset already exists, .clear() should only clear the current widget without resetting it.
These changes will be incorporated in ``v4``.

**Comment by ppizarror** [comment]
The new method now is:

```python
    def clear(self, reset=False) -> None:
        """
        Clears all widgets.

        .. note::

            This is applied only to the base Menu (not the currently displayed,
            stored in ``_current`` pointer); for such behaviour apply
            to :py:meth:`pygame_menu.Menu.get_current` object.

        :param reset: If ``True`` the menu also resets
        :return: None
        """
        if reset:
            self.full_reset()
        del self._widgets[:]
        del self._submenus[:]
        self._index = -1
        self._stats.clear += 1
        self._render()
```

**Comment by ppizarror** [comment]
From my perspective, having  ``reset=True`` is best and makes more sense (we would want to restore the state of the Menu to its origin)

**Comment by SANGERA2** [comment]
Nice idea having reset as a parameter! Thanks very much.

**Comment by ppizarror** [comment]
v3.5.3 published. v4 has this feature by default. Thanks!

**Comment by SANGERA2** [comment]
Thanks Pablo.
