### ISSUE TITLE
Other Programs

### ISSUE THREAD

**Issue by juulibauer** [ppizarror/pygame-menu#29]
Is it possible to start other python programs from pygame-menu?

**Comment by ppizarror** [comment]
Using subprocess i think?

```
import subprocess

def myfunction():
   p = subprocess.Popen(["yourfile.exe", fileName])
   # ... do other things while notepad is running
   returncode = p.wait() # wait for notepad to exit

# something like example 1
menu = pygameMenu.Menu(surface,
                       ...
                       )
menu.add_option("Execute yourfile", myfunction)  # Trigger function
```

**Comment by juulibauer** [comment]
It always gets me that error here. Can you help me?


_File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'function' is not iterable_

**Comment by ppizarror** [comment]
Check this gist i created
(https://gist.github.com/ppizarror/f78cf46fd3650181f7947fd4fdd3f490)[https://gist.github.com/ppizarror/f78cf46fd3650181f7947fd4fdd3f490]

**Comment by juulibauer** [comment]
perfect thanks :)

**Comment by juulibauer** [comment]
I guess it won't work for python applications?

**Comment by ppizarror** [comment]
Maybe you need to call a command check this gist:
https://gist.github.com/ppizarror/eceeeca337d9cd010cfb52a4b7c8a4af

Here I use .call() command, there you can execute commands (like py %file). For getting output you must use stdout argument.
https://docs.python.org/2/library/subprocess.html

**Comment by juulibauer** [comment]
It works now. Thank you so much :)

**Comment by ppizarror** [comment]
Nice! I'll close this issue by now 😄
