### ISSUE TITLE
How to get input from add_text_input?

### ISSUE THREAD

**Issue by majsterkovic** [ppizarror/pygame-menu#293]
`menu.add_text_input('Name ', default='John')`

How to get the value of this input?
name = ?

**Comment by ppizarror** [comment]
```python
my_text = menu.add_....
my_text.get_value()
```

**Comment by ppizarror** [comment]
See: https://pygame-menu.readthedocs.io/en/3.5.6/_source/widgets_textinput.html#pygame_menu.widgets.TextInput.get_value

**Comment by majsterkovic** [comment]
```python
name = menu.add_text_input('Name ', default='John')
user_name = name.get_value()
```
Thanks
