### ISSUE TITLE
Trying to remove buttons

### ISSUE THREAD

**Issue by RickyAsbury** [ppizarror/pygame-menu#295]
I'm trying to remove buttons on a menu; I tried using the remove_widget function; is there a specific thing I'm supposed to type for trying to do it that way or do I have to use something else?

**Comment by ppizarror** [comment]
menu.remove_widget(my_widget) should be fine

**Comment by RickyAsbury** [comment]
How would you get "my_widget" exactly did I have to do something before I
add the buttons in the menu?

**Comment by ppizarror** [comment]
you need the reference, there's two options:

1. mywidget= menu.add_.....
2. mywidget = menu.get_widget('mywidgetID')

**Comment by RickyAsbury** [comment]
Ok I'll try that tomorrow thank you

**Comment by ppizarror** [comment]
I've added the possibility to select the widgets and remove the widgets from the id. For example

```
menu.remove_widget('myWidgetID')
```

This is only a shorthand for ```menu.remove_widget(menu.get_widget('myWidgetID'))``` but it's easier to understand.
The new version v3.5.7 has been published :) I'll close this issue for now
