### ISSUE TITLE
Documentation differs from actual code

### ISSUE THREAD

**Issue by MathisFederico** [ppizarror/pygame-menu#296]
**Environment information**
Describe your environment information, such as:
- SO: win10
- python version: v3.7.7
- pygame version: v2.0.1
- pygame-menu version: v3.5.6

**Describe the bug**
Documentation differs from actual code, I want to use the Decorator API but it is not implemented in actual code ?

**To Reproduce**
See [the actual source code](https://github.com/ppizarror/pygame-menu/blob/3.5.6/pygame_menu/widgets/core/widget.py) vs [the documented source ](https://pygame-menu.readthedocs.io/en/latest/_modules/pygame_menu/widgets/core/widget.html#Widget).
Use ctrl + f and type 'get_decorator'. It is present in documentation but not in actual code.

**Expected behavior**
Decorator API to be in the actual code.

**Comment by MathisFederico** [comment]
Ah maybe it's because this isn't released yet ?

**Comment by MathisFederico** [comment]
Yeah just checked, present in latest but not in 3.5.6 !

**Comment by MathisFederico** [comment]
Built from source (4.0.0)
Can't wait for the release then !

**Comment by ppizarror** [comment]
The v4 is a complete revolution compared to v3. It would be excellent if you can test the new version. I'll publish a pre-release of the compiled whl for installing through pip if you like. V4 makes a lot of changes, considering the new frames (which can incorporate more widgets, decorators, drop selectors, etc)

**Comment by MathisFederico** [comment]
I am testing the new version for my application ! (Reinforcement learning for inventory management)
It will be open-source soon (When I finish the rendering and documentation, so around the end of the week/ weekend)
I'll send the link here if you'd like !
