### ISSUE TITLE
I can't input Latin Extended characters

### ISSUE THREAD

**Issue by PuffyPotato** [ppizarror/pygame-menu#297]
Hello,
I have this code:

`nick = menu.add_text_input('Name: ', default='John')`

In the game menu, it is impossible to input from keyboard characters like:

> ą, ę, ś, ć, ż, ź, ó, ł, ń

Is it possible to fix by adding some code or is it not supported by pygame-menu?

**Comment by ppizarror** [comment]
I just copied these characters and it worked

![image](https://user-images.githubusercontent.com/12925256/109437159-399c4d00-7a02-11eb-9dc3-f66ffd52e592.png)

Make sure the font that you are using supports these characters. TextInput uses "event.unicode" from event.key. Maybe these chars do not work...

**Comment by majsterkovic** [comment]
> I just copied these characters and it worked

This works for copying but not for typing.

**Comment by ppizarror** [comment]
Now unicode are supported in python 2.7:

![image](https://user-images.githubusercontent.com/12925256/109499903-42c60200-7a74-11eb-8465-b470836daa3a.png)

In python 3+ this is not a problem

**Comment by majsterkovic** [comment]
I found that Alt+a behaves like Ctrl+a (select all) for example.

**Comment by ppizarror** [comment]
> I found that Alt+a (ą) behaves like Ctrl+a (select all) for example.

Fixed, see #300

**Comment by ppizarror** [comment]
Can you test the #300 PR (pygame-menu v3)? I think it now works as intended

**Comment by PuffyPotato** [comment]
Yes, it works now. Thank you!

**Comment by ppizarror** [comment]
v3.5.8 uploaded to pypi & github.
Also, v4 has been updated too.

Greetings :)
