### ISSUE TITLE
Error in the docs.

### ISSUE THREAD

**Issue by GregSCooper2514** [ppizarror/pygame-menu#298]
Wrong description of title_font on page https://pygame-menu.readthedocs.io/en/3.5.6/_source/themes.html#pygame_menu.themes.Theme.
![Screenshot_2](https://user-images.githubusercontent.com/65116080/109432753-c99bc000-7a1d-11eb-8e14-ff873fadd14f.jpg)

**Comment by ppizarror** [comment]
Thanks, fixed!
