### ISSUE TITLE
Use same key to close menu and sub-menu (use ESC instead of BACK)

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#30]
Hello,

Is it possible to use the same key (e.g. ``ESC``) to close the main menu (``Menu()``) and a submenu (``TextMenu()``)?

I tried to set the variable ``MENU_CTRL_BACK``:
```
config_controls.MENU_CTRL_BACK = pygame.locals.K_ESCAPE
```

But after that, it is no more possible to close the main menu.

Thanks

**Comment by ppizarror** [comment]
I think somehow the mainloop of the previous menu brokes, or the pointer to the actual menu disappears, ¿What if you "print" the status of the events?

**Comment by anxuae** [comment]
I think that the reason is in the method ``_main``:

https://github.com/ppizarror/pygame-menu/blob/65249d351bf7604f319e2e752c638c42dae119e6/pygameMenu/menu.py#L562-L567

As I have defined the same key for ``MENU_CTRL_BACK``and ``MENU_CTRL_CLOSE_MENU``, the line 563 is always executed even if the main menu is displayed.

**Comment by anxuae** [comment]
It can be fixed by:

```
                elif event.key == _ctrl.MENU_CTRL_BACK and self._actual._prev is not None:
                    self.reset(1)
                elif event.key == _ctrl.MENU_CTRL_CLOSE_MENU and \
                        not self._closelocked:
                    onclose = self._actual._onclose
```

**Comment by ppizarror** [comment]
> It can be fixed by:
> 
> ```
>         elif event.key == _ctrl.MENU_CTRL_BACK and self._actual._prev is not None:
>             self.reset(1)
>         elif event.key == _ctrl.MENU_CTRL_CLOSE_MENU and \
>                 not self._closelocked:
>             onclose = self._actual._onclose
> ```

Could you create a new PR?
