### ISSUE TITLE
Remove annoying UserWarning

### ISSUE THREAD

**Issue by MathisFederico** [ppizarror/pygame-menu#305]
### **What version of pygame-menu are you using**
v4.0.0

### **Is your feature request related to a problem? Please describe.**

I'm always frustrated when a UserWarning is raised for a common behavior.

The following warning is raised when I use a scalar as column_max_width:
`UserWarning: column_max_width can be a single number if there is only 1 column, but there is 25 columns. Thus, column_max_width must be a vector of 25 items. By default a vector has been created using the same value for each column`

But having this value for every column is the desired behavior.

### **Describe the solution you'd like**

To remove this UserWarning, because I don't think it is really useful, but it is annoying for sure.
### 
**Describe alternatives you've considered**

I could build a Vector, but using a Vector with 25 same values seems a bit stupid.

**Comment by ppizarror** [comment]
I thought someone would dislike this jajaja. I'm removing that warning right now
