### ISSUE TITLE
Vertical frame usage

### ISSUE THREAD

**Issue by eforgacs** [ppizarror/pygame-menu#309]
Hi! I'm trying to implement a vertical frame within a menu,  but there are no examples of vertical frames in the example code. Would you be able to provide some guidance on how vertical frames are used in conjunction with the widgets that are contained within them? Thanks!

**Comment by ppizarror** [comment]
Hi, examples about vertical frame can be found in:
https://pygame-menu.readthedocs.io/en/4.0.0/_source/add_widgets.html#add-a-frame

I don't know if you considered these as examples; maybe the docs are not clear enough...

**Comment by ppizarror** [comment]
As always, any improvement to the library is welcome. Also, I've added a line that reminds users to check the widgets example docs

**Comment by eforgacs** [comment]
Okay! Thanks for the help, I'll be sure to check the docs, and I will be in touch if I have more questions.
