### ISSUE TITLE
How to add image on specific position

### ISSUE THREAD

**Issue by mrkprdo** [ppizarror/pygame-menu#310]
How do i place my BaseImage in the specific x,y position?

```
img = pygame_menu.baseimage.BaseImage("icon.png")
img.scale(0.3,0.3)
main.add.image(image_path=img.copy())
```

I know `pygame_menu.locals.POSITION_SOUTH` and positions alike exists, but this does not allow me to move images around on specific (x,y) position.

**Comment by ppizarror** [comment]
You can set them as float, (set_float()), them translate them. Floating
widgets do not contribute to menu sizing

**Comment by ppizarror** [comment]
As floating widgets consider the column/row layout position as default, I've added a new parameter to ``set_float`` method which set the initial position of the widget as (0, 0) (top-left position within the Menu). This will be added in v4.0.1.

```python
menu = MenuUtils.generic_menu(title='Example menu')
img = pygame_menu.BaseImage(pygame_menu.baseimage.IMAGE_EXAMPLE_PYGAME_MENU)
img.scale(0.3, 0.3)
image_widget = menu.add.image(image_path=img.copy())
image_widget.set_border(1, 'black')
image_widget.set_float(position_origin=True)
menu.render()
menu.mainloop(surface)
```

![image](https://user-images.githubusercontent.com/12925256/111926862-4ce48a80-8a8d-11eb-9402-c039a39bfd74.png)

Thus, the widget can be moved considering now a translation from the origin, for example:

```python
image_widget.translate(100, 100)
```

Generates:

![image](https://user-images.githubusercontent.com/12925256/111926903-79000b80-8a8d-11eb-909b-0a2a323d0df3.png)

Also, negative translation is accepted:

```python
image_widget.translate(-50, 0)
```

![image](https://user-images.githubusercontent.com/12925256/111926948-a8167d00-8a8d-11eb-9334-cf76c70f8259.png)

**Comment by mrkprdo** [comment]
Thank you. Got it to work now.
I just wish to add this kind of example to the documentation. 
Have a nice day!

**Comment by ppizarror** [comment]
Feel free to push any changes you want to the library, the documentation is on https://github.com/ppizarror/pygame-menu/tree/master/docs/_source

Greetings :)

**Comment by ppizarror** [comment]
New version v4.0.1 already published to PyPI, incorporated also macOS support for m1 & intel
