### ISSUE TITLE
Table().add_row() widget list as stack of widgets

### ISSUE THREAD

**Issue by mrkprdo** [ppizarror/pygame-menu#317]
```bash
  File "/usr/local/lib/python3.9/site-packages/pygame_menu/widgets/widget/table.py", line 351, in add_row
    assert isinstance(c, Widget)
AssertionError
```

As the title says, `add_row(widget_list)` fails assertion.
Perhaps something was changed, as the [annotation](https://github.com/ppizarror/pygame-menu/blob/d29b00493bc91512e5555086d5e4b35fa14ab77a/pygame_menu/widgets/widget/table.py#L238) suggests:
```
:param cells: Cells to add. This can be a tuple or list of widgets, string, numbers, boolean values or images. 
Also a Frame row can be added
```

Any thoughts?

**Comment by ppizarror** [comment]
Hi, can you share how you're calling the method? (a toy example)

**Comment by mrkprdo** [comment]
Ahh i think i got it to work, but its not what im expecting to render.
The widgets are arranged side by side rather than regular stack as if is not in a table.

(Expectation)
![Screen Shot 2021-04-05 at 23 42 07](https://user-images.githubusercontent.com/15664355/113655871-ad1c2480-9668-11eb-953b-c0a7e76ab65d.png)

(Actual)
![Screen Shot 2021-04-05 at 23 40 19](https://user-images.githubusercontent.com/15664355/113655749-64fd0200-9668-11eb-992b-e68b221dd743.png)


```python
import pygame
import pygame_menu

x = y = 400

class Sample:
    def __init__(self):
        pygame.init()
        surface = pygame.display.set_mode((x,y))

        theme = pygame_menu.themes.Theme(
            title_font_size=8,
            title_bar_style=pygame_menu.widgets.MENUBAR_STYLE_SIMPLE,
            background_color=(116, 161, 122),
            title_background_color=(4, 47, 58),
            title_font_color=(38, 158, 151),
            widget_selection_effect=pygame_menu.widgets.NoneSelection()
        )

        main_menu = pygame_menu.menu.Menu(
            title='Main Menu',
            height=x,
            width=y,
            theme=theme
        )

        table = main_menu.add.table('tbl1')

        widget_list = list()

        for i in range(3):
            widget = main_menu.add.button(f'Button {i}',run_func)
            widget_list.append(widget)
        
        table.add_row(tuple(widget_list))

        main_menu.mainloop(surface,disable_loop=False)

def run_func():
    print("Clicking")

if __name__ == "__main__":
    sample = Sample()
```

Also, the widget interaction does not work when its inside the table, (can't select buttons)

PS: l'll change title, removing bug maybe.

**Comment by ppizarror** [comment]
Currently, the table does not support events handling as this method removes the widget from the Menu https://github.com/ppizarror/pygame-menu/blob/d29b00493bc91512e5555086d5e4b35fa14ab77a/pygame_menu/widgets/widget/table.py#L370-L375

Currently, I cannot remember why I took that decision ... you could try to commend those lines and see what's the output. Also, 
![image](https://user-images.githubusercontent.com/12925256/113657186-654acc80-966b-11eb-8222-158e5853ae69.png)

This example makes more sense as you're adding a single row composed of 3 columns, this function (add_row) accepts a list and creates N columns if the vector has N items. Thus, you need to create 3 rows to add those items...

Another solution is using a vertical frame. Vertical frames accepts widgets and events, also they can have properties such as border, background color, etc.

**Comment by ppizarror** [comment]
For example,

```python
import pygame
import pygame_menu

x = y = 400

class Sample:
    def __init__(self):
        pygame.init()
        surface = pygame.display.set_mode((x,y))

        theme = pygame_menu.themes.Theme(
            title_font_size=8,
            title_bar_style=pygame_menu.widgets.MENUBAR_STYLE_SIMPLE,
            background_color=(116, 161, 122),
            title_background_color=(4, 47, 58),
            title_font_color=(38, 158, 151),
            widget_selection_effect=pygame_menu.widgets.NoneSelection()
        )

        main_menu = pygame_menu.menu.Menu(
            title='Main Menu',
            height=x,
            width=y,
            theme=theme
        )

        table = main_menu.add.table('tbl1')

        for i in range(3):
            widget = main_menu.add.button(f'Button {i}',run_func)
            table.add_row(widget)

        main_menu.mainloop(surface,disable_loop=False)

def run_func():
    print("Clicking")

if __name__ == "__main__":
    sample = Sample()

```

![image](https://user-images.githubusercontent.com/12925256/113657515-1a7d8480-966c-11eb-9b1c-8e5a9510dc00.png)

If the documentation is not clear enough you can think of a better way to explain this issue and avoiding further confussion

**Comment by mrkprdo** [comment]
Given with table disabling interactions, i may have to stick normal way of stacking widgets. However what im trying to achieve here is something like this:

![113655871-ad1c2480-9668-11eb-953b-c0a7e76ab65d.png](https://user-images.githubusercontent.com/15664355/113658376-f02cc680-966d-11eb-860e-b2f51f313199.png)

Where i have a top/bottom widgets, and list of multiple widgets in the middle. This activates long scroll menu, but want i wanted is only scroll thru the center row.

**Comment by ppizarror** [comment]
You may use a vertical frame, which contains 3 items
1. label
2. another vertical frame with max_height, making it scrollable
3. label

**Comment by ppizarror** [comment]
I'll close this issue by now. If there's any suggestion or fix please create a new post or PR, thanks

**Comment by mrkprdo** [comment]
Hey, Thanks man. I have tested the vertical frame but had ran into some issues. I'll post it if i can. I just paused my project for a while as i am working on the hardware parts. Cheers!
