### ISSUE TITLE
Running button function on start.

### ISSUE THREAD

**Issue by SoupOrSoda** [ppizarror/pygame-menu#319]
- OS: win
- python version: v3.9.2
- pygame version: v2.0.1
- pygame-menu version: v4.0.2

**Describe the bug**
I have a class which controls the menu
```
class MainMenu():
        global particleSys
        def __init__(self):
              self.bgimage = pygame.image.load(r'img/titlescreen.png')
              self.rectBGimg = self.bgimage.get_rect()
             
              self.bgY1 = 0
              self.bgX1 = 0
 
              self.bgY2 = 0
              self.bgX2 = self.rectBGimg.width
 
              self.moving_speed = 1
         
        def update(self):
            self.bgX1 -= self.moving_speed
            self.bgX2 -= self.moving_speed
            if self.bgX1 <= -self.rectBGimg.width:
                self.bgX1 = self.rectBGimg.width
            if self.bgX2 <= -self.rectBGimg.width:
                self.bgX2 = self.rectBGimg.width

        def load_multiplayer_menu(self, mm):
            print("Loaded multiplayer menu.")
            print("Test!")
            mm.clear
            mm.add.text_input("Server address: ", default="beta.bacterium.xyz", maxchar=50)

        def load_singleplayer_menu(self, mm):
            print("Singleplayer menu loaded.")

        def closeMainMenu(self, mainMenu):
            print("Test!")
    
        def options(self):
            pygame.display.set_caption("Bacterium")
            mainMenu = pygame_menu.Menu('Bacterium', 500, 400, theme=THEME_DARK)
            mainMenu.add.text_input('Name: ', default='Player'+str(random.randint(1000,9999)), maxchar=16)
            mainMenu.add.button('Singleplayer', self.load_singleplayer_menu(mainMenu))
            mainMenu.add.button('Mutiplayer', mainMenu.clear, self.load_multiplayer_menu(mainMenu))
            mainMenu.add.button('Quit', mainMenu.clear)

            mainMenu.mainloop(screen, bgfun = self.background_task)

        def background_task(self):
            menu.update()
            menu.render()
            particleSys.create()
            
        def render(self):
            
            screen.blit(self.bgimage, (self.bgX1, self.bgY1))
            screen.blit(self.bgimage, (self.bgX2, self.bgY2))
```
This code runs load_multiplayer_menu and load_singleplayer_menu on start.

**To Reproduce**
Create a class that handles this, and run it.

**Expected behavior**
Only running the function when the button is clicked

**Additional context**
n/a

**Comment by ppizarror** [comment]
Hi, the first argument of the add.button method is a function, and the following *args are the arguments of such function, in your example:

```mainMenu.add.button('Singleplayer', self.load_singleplayer_menu(mainMenu))```
You're passing to the function basically ``None``, as calling  ``self.load_singleplayer_menu(mainMenu)``returns such value. For solving this issue, you should have this:

```mainMenu.add.button('Singleplayer', self.load_singleplayer_menu, mainMenu)```

Thus, if clicking that button the ``self.load_singleplayer_menu`` function is executed with ``mainMenu``as argument.
Anyway, I think a better approach is using submenus rather than removing the main menu instance... for example

```python
mm = Menu(...)

sp = Menu('Singleplayer', ...)
mp = Menu('Multiplayer', ....)

mm.add.button('Singleplayer', ...)
mm.add.button('Multiplayer', ...)
```

This does not break the logic of the menu, and is way easier to code

**Comment by ppizarror** [comment]
Did you resolve your issue? @SoupOrSoda

**Comment by ppizarror** [comment]
I'll close this issue, if you have any other issue please create a new post or PR with features

**Comment by SoupOrSoda** [comment]
Thank you, this works perfectly
