### ISSUE TITLE
ToggleSwitch with selection_effect=None

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#325]
**Environment information**
Describe your environment information, such as:
- SO: Mac OSX
- python version: v3.7.7
- pygame version: v2.0.1
- pygame-menu version: v4.0.3

**Describe the bug**

In the example `pygame_menu.examples.multi_input`, one of the `toggle_switch` has the parameter with `selection_effect=None`, however it seems that it is still possible to select the toggle switch:

```python
    # Create switch
    settings_menu.add.toggle_switch('First Switch', False,
                                    toggleswitch_id='first_switch',
                                    selection_effect=None)
```

Is it normal?

**Comment by ppizarror** [comment]
Do you mean having the white color in the text? The selection color of the font does not rely on the selection effect. The selection color is stored in ``widget.set_font(...)`` method.

![image](https://user-images.githubusercontent.com/12925256/116478958-ecdfc180-a84c-11eb-9f64-b1e115846508.png)

**Comment by ppizarror** [comment]
For solving this issue, maybe selection object can have a bool parameter named ``apply_font_color``. Thus, widget method

```python
  def get_font_color_status(self, check_selection: bool = True) -> ColorType:
      """
      Return the Widget font color based on the widget status.

      :param check_selection: If ``True`` font is also checked if selected
      :return: Color by widget status
      """
      if self.readonly:
          if self._selected:
              return self._font_readonly_selected_color
          return self._font_readonly_color
      if self._selected and check_selection:
          return self._font_selected_color
      return self._font_color
```

Should be changed to:

```python
def get_font_color_status(self, check_selection: bool = True) -> ColorType:
    """
    Return the Widget font color based on the widget status.

    :param check_selection: If ``True`` font is also checked if selected
    :return: Color by widget status
    """
    if self.readonly:
        if self._selected:
            return self._font_readonly_selected_color
        return self._font_readonly_color
    if self._selected and check_selection and self._selection_effect.apply_font_color:
        return self._font_selected_color
    return self._font_color
```

Obviously, for NoneSelection the new parameter is False. Let me know if this is a good approach

**Comment by ppizarror** [comment]
See #328 and let me what you think 😎

**Comment by anxuae** [comment]
Yes it sound great! thanks a lot.
