### ISSUE TITLE
ToggleSwitch should not require to click on the left or right of the widget

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#326]
Hi @ppizarror 

I have experimented the ToggleSwitch widget some days ago.
It is a really nice improvement! thanks for that.

One thing I've found not natural comparing with usual UIs: I need to click on the left or the right of the widget in order to toggle it. As there are only 2 states (which is not the case with selector), it should be more intuitive that the switch toggles whatever the place where the user is clicking.

I'm just a suggesting ;-) .

**Comment by ppizarror** [comment]
Yes, maybe it's not necessary to click right/left positions to change it.

So, I'll add a new parameter to modify this feature, If ToggleSwitch(``single_click=True``) the toggle will switch only with 1 click between 2 states (basically, advances state_(i+1) for N states in a list.

``single_click`` will be False by default I guess?

**Comment by ppizarror** [comment]
Let me know if #327 is clear and solves this issue 😄

**Comment by anxuae** [comment]
Hi @ppizarror 
I have tested your PR, it is working fine. Thank you!
Maybe for the toggle switch `single_click=True` by default? I don't know what is the best.

**Comment by ppizarror** [comment]
PR pushed :)

**Comment by ppizarror** [comment]
I'll upload the new version 4.0.4 with the bug fixes and new features. Greetings
