### ISSUE TITLE
get_cursor() removed from SDL2

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#330]
**Environment information**
- OS: Ubuntu 20.04
- python version: v3.7
- pygame version: v2.0.0
- pygame-menu version: v4.0.4

**Bug description**

In SDL2, the `pygame.mouse.get_cursor()` function has been removed, see https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.get_cursor .

To be compatible, `pygame-menu` shall not use the `get_cursor()` function. Currently the following line throw an error:

https://github.com/ppizarror/pygame-menu/blob/9e21edadbaf4b8e013d2590d0941c9b0377ba5be/pygame_menu/widgets/core/widget.py#L598-L602

```python
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/menu.py", line 2590, in update
    widget._check_mouseover(event)
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/widgets/core/widget.py", line 679, in _check_mouseover
    self.mouseover(event, check_all_widget_mouseleave)
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/widgets/core/widget.py", line 600, in mouseover
    previous_cursor = pygame.mouse.get_cursor()  # Previous cursor
TypeError: The get_cursor method is unavailable in SDL2
```

**Comment by anxuae** [comment]
Hi @ppizarror,

This is a limitation of the pygame 2.0.0 / SDL 2.0.12 library
No problem with pygame 2.0.1 / SDL 2.0.14

It seems that pygame documentation is not up to date

**Comment by ppizarror** [comment]
I should add a exception catch as pygame-menu must work with all versions.
