### ISSUE TITLE
Make touchscreen application compatible with SDL1 and SDL2

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#331]
Currently a touch screen is usable using 2 different kinds of events depending on SDL version:

- SDL1 (pygame 1.9.6): using event MOUSEBUTTONUP and MOUSEBUTTONDOWN
- SDL2 (pygame 2.0.1): using event FINGERUP and FINGERDOWN 

Managing the both kings of event permits to develop a software compatible with SDL1 and SDL2 library running on a touchscreen device.
However, `pygame-menu` does not permit it. I've got the following error when I set `touchscreen=True`.

```python
Traceback (most recent call last):
  File "/Volumes/DATA/Projects/pibooth/pibooth/booth.py", line 371, in main_loop
    self._menu = PiConfigMenu(self._pm, self._config, self, self._window)
  File "/Volumes/DATA/Projects/pibooth/pibooth/config/menu.py", line 101, in __init__
    onclose=self._on_close)
  File "/Users/antoine/.virtualenvs/pygame1/lib/python3.7/site-packages/pygame_menu/menu.py", line 568, in __init__
    assert version_major >= 2, 'touchscreen is only supported in pygame v2+'
AssertionError: touchscreen is only supported in pygame v2+
```

Is it possible to relax this constraints?

**Comment by ppizarror** [comment]
aah I see, you're right

then simply commit a PR removing that assertion :)

**Comment by ppizarror** [comment]
Fixed. If you've found any issue please let me know. I'll upload a new version by the end of this week I guess
