### ISSUE TITLE
mainloop closes after first loop in 4.0.5

### ISSUE THREAD

**Issue by yagui** [ppizarror/pygame-menu#336]
After testing 4.0.5, the mainloop only runs once.

I think is because the third condition added here:
https://github.com/ppizarror/pygame-menu/blob/87f8090b56196f11fcdd8f68c1413b2dfeaeaa8e/pygame_menu/menu.py#L2815

Tested with the 'simple' example and it only run once. If I remove that condition everything works again.

**Comment by ppizarror** [comment]
Hi, thanks for posting this critical bug. I've patched it and added proper testing; I did not test the main loops for more than 2 frames.

**Comment by ppizarror** [comment]
Updated PyPI to v4.0.6, let me know if there's any issue =)

**Comment by yagui** [comment]
Thank you for fixing it so quickly :)
