### ISSUE TITLE
GPIO support 

### ISSUE THREAD

**Issue by XOR0831** [ppizarror/pygame-menu#358]
I am trying to create a menu that can be controlled (left, right, up, down, enter) using GPIO. I tried to use pyautogui for emulating a keyboard keypress but the pygame_menu selector is not moving. I checked the pygame events and i have successful fired and received a keyboard keypress event. I just want to have an option to map which GPIO button corresponds to left, right, up, down, enter.

**Comment by ppizarror** [comment]
Hi, you can update the controls to anything you want; for example:

```python
import pygame_menu.controls as ctrl
ctrl.KEY_LEFT = gpio.left # I don't know the real value...

... the rest of the menu application
```

See for example the test where the controls are remapped, https://github.com/ppizarror/pygame-menu/blob/cde28c272d79b1d12c9f2fda9fcf92800d883b73/test/test_controls.py#L43-L81.

Let me know if this approach works for you

**Comment by ppizarror** [comment]
The whole menu library should rely on the controls module (https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/controls.py). If there's a widget that does not work as intended, just create a new issue and I'll quickly patch it.

**Comment by XOR0831** [comment]
Hi, GPIO does not have a fixed value like keyboard events. This approach won't work so i'll go for emulating keyboard events from GPIO. Also, I created a bug report #359. Can you please check?

**Comment by XOR0831** [comment]
Closing this requests.
