### ISSUE TITLE
I get this error when moving over a widget

### ISSUE THREAD

**Issue by MayuSakurai** [ppizarror/pygame-menu#366]
```
/home/mayu/.local/lib/python3.8/site-packages/pygame_menu/utils.py:623: UserWarning: could not establish widget cursor, invalid value ((16, 16), (0, 0), (0, 0, 64, 0, 96, 0, 112, 0, 120, 0, 124, 0, 126, 0, 127, 0, 127, 128, 124, 0, 108, 0, 70, 0, 6, 0, 3, 0, 3, 0, 0, 0), (192, 0, 224, 0, 240, 0, 248, 0, 252, 0, 254, 0, 255, 0, 255, 128, 255, 192, 255, 224, 254, 0, 239, 0, 207, 0, 135, 128, 7, 128, 3, 0))
  warn(f'could not establish widget cursor, invalid value {cursor}')

The kernel process exited. (1)

````

I get that error when moving the cursor above a widget. Any way to solve this?

**Comment by ppizarror** [comment]
Hi! This error happens in any example? Can you provide a working example to test this issue?
Greetings

**Comment by MayuSakurai** [comment]
Oh, never mind! I was using older pygame!

**Comment by MayuSakurai** [comment]
That happened with all examples though. I was just using Pygame 1.9.4.

**Comment by ppizarror** [comment]
pygame<2 uses a bitmap matrix to define cursors (yes, really low-level definition of a cursor). That was the problem I guess. Just to clarify, the program broke, or it was just a console warning?

**Comment by MayuSakurai** [comment]
It was a console warning, but it terminated the program.

**Comment by MayuSakurai** [comment]
So the solution: Update Pygame
