### ISSUE TITLE
Menu not resizing when there is the pygame.RESIZABLE flag.

### ISSUE THREAD

**Issue by leha-code** [ppizarror/pygame-menu#368]
is it possible to resize the menu somehow? btw my code is at https://github.com/MIneshaft-game/Mineshaft just clone it and run main.py

**Comment by ppizarror** [comment]
Hi. Currently, there's no way to resize the menu unless it is destroyed/re-created again (while using the same widgets). However, that's a nice idea. As soon as I finish my other projects, I'll work on this feature.

**Comment by leha-code** [comment]
```
pygame 2.0.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    import pygame_menu
  File "/home/ leha2/pygame-menu-fix-build/pygame_menu/__init__.py", line 72, in <module>
    import pygame_menu.font
  File "/home/leha2/pygame-menu-fix-build/pygame_menu/font.py", line 64, in <module>
    import pygame.font as __font
ImportError: /usr/lib/python3/dist-packages/pygame/font.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```
(on linux with sudo)

**Comment by ppizarror** [comment]
Excellent, thus I'll push this new version to PyPI. Feel free to create a new issue if you encounter any error or a PR if you want to add a feature.

Greetings :)
