### ISSUE TITLE
How to place button in top

### ISSUE THREAD

**Issue by leestarb** [ppizarror/pygame-menu#371]
Hello there
How can I put new button in the top position of menu where is some buttons already
**Howw**

**Comment by ppizarror** [comment]
Hello, I've updated the library to simplify the positioning of the elements (#372).

To place your widgets anywhere (current v4.1.5), you must set them as ``float``, for example:

```python
mywidget = menu.add.label(...)
mywidget.set_float(True)
```

Now, the widget does not contribute size to the menu, and it can be moved using ``widget.translate`` method. For example:

```python
menu = pygame_menu.Menu(
    height=480,
    theme=my_theme,
    title='',
    center_content=False,
    width=640
)

menu.add.label(
    'My App',
    background_color='#333333',
    background_inflate=(30, 0),
).set_float().translate(0, 10)

label = menu.add.label(
    'Lorem ipsum',
    font_name=pygame_menu.font.FONT_OPEN_SANS_ITALIC,
    font_size=25)
label.set_float()
label.rotate(90)
label.translate(300, 160)
```

The new version (4.1.6) adds ``float`` to widgetmanager methods. #372 also adds a new example:

```python
import pygame_menu
from pygame_menu.examples import create_example_window

# Create the surface
surface = create_example_window('Example - Widget Positioning', (640, 480))

# Create a custom theme
my_theme = pygame_menu.themes.THEME_DARK.copy()
my_theme.title = False  # Hide the menu title

menu = pygame_menu.Menu(
    height=480,  # Use full-screen
    theme=my_theme,
    title='',
    center_content=False,
    width=640
)

menu.add.label(
    'My App',
    background_color='#333',
    background_inflate=(30, 0),
    float=True  # Widget does not add size to the menu
).translate(0, 10)

label = menu.add.label(
    'Lorem ipsum',
    float=True,
    font_name=pygame_menu.font.FONT_OPEN_SANS_ITALIC,
    font_size=25)
label.rotate(90)
label.translate(300, 160)

# Button options
b1 = menu.add.button(
    'Main Menu',
    lambda: print(f'My method'),
    align=pygame_menu.locals.ALIGN_LEFT,
    float=True,
    selection_color='#fff'
)
b1.translate(10, 170)
b2 = menu.add.button(
    'Exit',
    pygame_menu.events.EXIT,
    align=pygame_menu.locals.ALIGN_LEFT,
    float=True,
    selection_color='#fff'
)
b2.translate(10, 235)

# Bottom scrollable text
f = menu.add.frame_v(
    background_color='#6b6e5e',
    border_color='#36372f',
    border_width=1,
    float=True,
    height=480,
    max_height=100,
    width=200
)
f.translate(220, 390)
labels = [menu.add.label(f'  Lorem ipsum #{i}', font_size=15, font_color='#000000', padding=0) for i in range(20)]
for j in labels:
    f.pack(j)

if __name__ == '__main__':
    menu.mainloop(surface)
```

Which should return:

<img width="752" alt="example_other_widget_positioning" src="https://user-images.githubusercontent.com/12925256/140254106-edf82ffa-ce79-41e7-9836-931dc8ad546e.png">

The only difference between 4.1.5 and 4.1.6 is that ``float=True`` is not an argument for widgetmanager methods. Also, v4.1.6 adds support for minified colors, so, ``#fff`` is converted to ``#ffffff`` and so on..

Let me know if these methods solves your issue. If so, I'll publish a new version

**Comment by leestarb** [comment]
Okay, it solved my problem, thanks!
However, I dont think that its really good method?

**Comment by ppizarror** [comment]
You can also set the position considering the top left menu position using set_float(origin_position=True) and translate considering that fixed origin. Also you can suggest new features and discuss the behavior of the methods of you have any idea.


Greetings
