### ISSUE TITLE
How do I exit the menu and start the game?

### ISSUE THREAD

**Issue by larryw3i** [ppizarror/pygame-menu#380]
May I ask a somewhat retarded question? how do I exit the menu and start the game?   
e.g   
```python
surface.fill((255, 255, 255)) # exit menu and fill white
```  
I am a pure novice, thanks.

**Comment by ppizarror** [comment]
Hello, to control the menu behavior you have 2 options:

1. Delegate the mainloop responsibility to the menu. There, on each frame, the menu can execute a particular method. See the ``draw_background`` method.
2. You can control the mainloop (aka, the while True) by manually drawing the menu using "menu.draw(surface)" and update "menu.update(events).

See https://pygame-menu.readthedocs.io/en/4.2.3/_source/create_menu.html#display-a-menu for more info.

Also, you can look at the examples: https://pygame-menu.readthedocs.io/en/4.2.3/_source/gallery.html. For example, timer_clock uses option 2.

**Comment by larryw3i** [comment]
@ppizarror thank you for your help.
