### ISSUE TITLE
How to start the game from a menu?

### ISSUE THREAD

**Issue by TheKnight1993** [ppizarror/pygame-menu#381]
I have been programming a menu for a game using pygame-menu, although when trying to run a function using a button I can't seem to let it show a different screen. I have done everything correctly, followed the documentation for displaying the menu with a loop managed outside of the menu. How does one make a game run from a menu?

**Comment by TheKnight1993** [comment]
Update on this, I've put the function that disables the menu and should show a different colour screen into a button in the menu. Whenever I put it as an option for that button, the function gets called immediately, and never gets to repeat the action.

**Comment by larryw3i** [comment]
Good question! view issue https://github.com/ppizarror/pygame-menu/issues/380 I submitted,   
View https://github.com/ppizarror/pygame-menu/issues/380 and use second method, then, add your code at `while` loop area. the basic logic of pygame is: write each frame.    
view example:
https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/examples/game_selector.py#L89
or view my code: 
https://github.com/larryw3i/primaryschool/blob/main/primaryschool/subjects/yuwen/g_pinyin_missile/__init__.py#L291

**Comment by ppizarror** [comment]
Hello, to control the menu behavior you have 2 options:

1. Delegate the mainloop responsibility to the menu. There, on each frame, the menu can execute a particular method. See the ``draw_background`` parameter.
2. You can control the mainloop (aka, the while True) by manually drawing the menu using "menu.draw(surface)" and update "menu.update(events).

See https://pygame-menu.readthedocs.io/en/4.2.3/_source/create_menu.html#display-a-menu for more info.

Also, you can look at the examples: https://pygame-menu.readthedocs.io/en/4.2.3/_source/gallery.html. For example, timer_clock uses option 2.

**Comment by ppizarror** [comment]
Hello. If you have any other questions, just create a new issue. I'm going to close this one. Greetings 😄
