### ISSUE TITLE
Typo In Documentation

### ISSUE THREAD

**Issue by ThePeeps191** [ppizarror/pygame-menu#384]
[Page](https://pygame-menu.readthedocs.io/en/4.2.4/#first-steps)

It says **That why pygame-menu was designed.**, shouldn't it be **That __was__ why pygame-menu was designed.**

**Comment by ppizarror** [comment]
Hi. Thanks! If you have any other suggestion or spot an error just create a new issue. Greetings 😀 🍔

**Comment by ThePeeps191** [comment]
Is there any way I could make a pull request or fix it?

**Comment by ppizarror** [comment]
Sure. You can click on any "edit on Github". That will create a fork of the library into your account, and then you can create a PR to fix this.

![image](https://user-images.githubusercontent.com/12925256/153775629-1df58d20-e806-4ded-a7c3-f3eb9c7784c1.png)

**Comment by ThePeeps191** [comment]
Ok, thanks!

**Comment by ThePeeps191** [comment]
I've made Pull Request #385
