### ISSUE TITLE
Add py.typed

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#388]
**Is your feature request related to a problem? Please describe.**
In order for Mypy to use the typing information of this project, you need to include a blank file called `py.typed` along the code, to comply with PEP 561 (https://www.python.org/dev/peps/pep-0561/). Otherwise Mypy skips this library in the type analysis.

**Describe the solution you'd like**
Add a blank `py.typed` file and package it along the code.

**Comment by ppizarror** [comment]
Hi. Can you create a new PR? Does setup.py file must be updated?

**Comment by vnmabus** [comment]
I can confirm that now it works!
