### ISSUE TITLE
Redirect pygame to a framebuffer

### ISSUE THREAD

**Issue by mrkprdo** [ppizarror/pygame-menu#391]
Hey @ppizarror, its been a year that I explored this cool module and its time to play around with it again.
I had a Radxa Zero that can run framebuffer on fb1, I was looking to get it to work with small lcd screen. With Pi, i can be set a config to start on that screen, on this board i still have to figured that one out.

Going back to this request, is there a possibility that we can pass pygame's .get_buffer() and implement here in pygame_menu?

I am thinking of getting Surface instance and get_buffer() write it directly to /dev/fb1 and run pygame on the small screen?

Is that something feasible?

**Comment by ppizarror** [comment]
Hi. I don't know how to use the get_buffer() object. Is it a method to retrieve a surface? How exactly it would be used by the menu?

**Comment by ppizarror** [comment]
Hi, any updates or example? Greetings!

**Comment by ppizarror** [comment]
Hi @mrkprdo I'll close this issue for now. If you have any news, let me know!! Greetings 😄
