### ISSUE TITLE
Selector and Joystick

### ISSUE THREAD

**Issue by AdamCyffka** [ppizarror/pygame-menu#392]
Hey, is there a way to override default enter and arrows keys for selector component? We would like to use joystick functions from pygame.

**Comment by ppizarror** [comment]
Yes sure, you can override any control. See https://github.com/ppizarror/pygame-menu/blob/master/test/test_controls.py#L46-L78

For such purpose you must:
```python
import pygame_menu.controls as ctrl
ctrl.KEY_APPLY = pygame.K_END
```

**Comment by ppizarror** [comment]
Can you provide a minimal working example?

**Comment by ppizarror** [comment]
Hi @AdamCyffka, any updates?

**Comment by ppizarror** [comment]
I'll close this issue for now. If you have any updates, let me know. Greetings!

**Comment by AdamCyffka** [comment]
Hey, we had taken a break on our project. To come back to our problem, here is a video that will be more telling of the problem with our joystick. When we go left and then return to the center, it goes to the left and then to the right and not left and nothing. Do you have any idea?

https://streamable.com/l75kqh
