### ISSUE TITLE
Function `is_callable` does not accept callable objects

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#394]
**Describe the bug**
The `is_callable` function is supposed to check that an object is callable, for example to add it as a button action. There are two problems with it:

1. There is already a builtin to do this: `callable`.
2. The `is_callable` function is more restrictive than `callable`: it only allows functions, methods and `partial` objects. It does not allow objects with a `__call__` method, for no particular reason.

I think that unless there is a powerful reason not to, the `is_callable` function should be replaced by the `callable` builtin.

**Comment by ppizarror** [comment]
Hi, that method was inherited from previous versions to support python 2. Feel free to create a new pull request with such feature
