### ISSUE TITLE
Disable scrollbars?

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#396]
I am trying to adjust the size of the menu to its contents. In order to do that, I am using the following code:
```python
widgets_size = menu.get_size(widget=True)
menu.resize(*widgets_size)
```
The problem is that the scrollbars appear and hide part of the widgets. I tried using
```python
menu.get_scrollarea().hide_scrollbars(pygame_menu.locals.ORIENTATION_HORIZONTAL)
menu.get_scrollarea().hide_scrollbars(pygame_menu.locals.ORIENTATION_VERTICAL)
```
to get rid of those, but they still appear. I also tried to set the scrollbar thickness to 0 in the theme, but that causes an exception.

Is there a way to disable scrollbars in a particular menu or theme?

**Comment by ppizarror** [comment]
I found what whas the error. The scrollbars were hidden after you called these functions, but shortly after the menu updated the rect size, dinamically changing the scrollbars visibility.

To solve this issue, I introduced the force param on .show() and .hide() scrollbar methods. Thus, hide_scrollbars call .hide with ``force=True``.

Also, I improved ``Scrollarea.get_view_rect`` method. Also I've added ``SCROLLAREA_POSITION_NONE`` as a valid position for ``theme.scrollarea_position``.

See #397 for more details. Let me know if this solves your issue.

**Comment by vnmabus** [comment]
It looks like both options work!

**Comment by ppizarror** [comment]
I'll merge asap. If you encounter any other issue please let me know. If you need a new PyPI version I'll release v4.2.7

**Comment by vnmabus** [comment]
Thank you!
