### ISSUE TITLE
Widget selection effect size not taken into account when determining widget size

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#405]
**Environment information**
Describe your environment information, such as:
- SO: linux
- python version: v3.8
- pygame version: v2.1.0
- pygame-menu version: v4.2.7

**Describe the bug**
The size of the widget selection effect is not taken into account when computing the size of the widgets with `menu.get_size(widget=True)`. Thus, adjusting the menu size to the widgets is more difficult than necessary.

**To Reproduce**
Execute the following code:
```python
import pygame
import pygame_menu

pygame.init()
surface = pygame.display.set_mode((600, 400))


def start_the_game():
    # Do the job here !
    pass


theme = pygame_menu.themes.THEME_BLUE.copy()
theme.title = False
theme.scrollarea_position = pygame_menu.locals.SCROLLAREA_POSITION_NONE
theme.widget_selection_effect = pygame_menu.widgets.LeftArrowSelection(
    arrow_right_margin=50,
)

menu = pygame_menu.Menu(
    'Welcome',
    100,
    100,
    theme=theme,
)

menu.add.button('Play', start_the_game)
menu.add.button('Quit', pygame_menu.events.EXIT)

size = menu.get_size(widget=True)
menu.resize(*size)

menu.mainloop(surface)
```

The above code tries to adjust the size of the menu to the size of the widgets. Instead, the generated menu looks like this:

![Captura de pantalla de 2022-05-01 16-18-11](https://user-images.githubusercontent.com/2364173/166150005-9c4123e4-72ae-4fa3-b190-a4dff746d6b0.png)

**Expected behavior**
The size of the widget selection effect should be taken into account by `menu.get_size(widget=True)`, and thus no widget should be truncated.

**Comment by vnmabus** [comment]
I can confirm that PR #406 solves my original problem.

**Comment by ppizarror** [comment]
Nice. Merged! I'll create a new version asap
