### ISSUE TITLE
Proper support for multiline labels

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#407]
**Is your feature request related to a problem? Please describe.**
Currently real multiline labels are not supported. If one activates word wrapping, several label widgets are created instead, one per line. Thus, it is not possible, for example, to change the text of the label programmatically with word-wrapping, unless you remove every label and re-add them.

**Describe the solution you'd like**
What I want is a widget to display multiline messages. In particular, I want to reimplement the following message display as a `pygame_menu` widget:

https://user-images.githubusercontent.com/2364173/166908206-eaac1ad9-6a81-48cd-8de1-4ffc2a44929e.mp4

As you can see, this displays multiline messages of variable length, doing word-wrapping and animating the text. This widget can speed up the animation when the enter key is pressed, as well as changing to the next page of text when the enter key is pressed at the end.

If the number of lines exceed the available lines, it should mark it somehow (with an arrow maybe) and allow the user to move the lines upwards / replace existing text to put the new ones (this is currently not implemented).

**Describe alternatives you've considered**
I was trying to implement this as my own widget, when I noticed that the existing `Label` object partially implements multiline support, but only at creation time. I think that it would be better to implement multiline support in the `Label` widget directly. The other features could probably be implemented in a `Label` subclass (or as a composite `Widget` with a label as one of its members) if they are not deemed general enough.

**Comment by ppizarror** [comment]
What are you refering to get the right width? ``max(self._font.size(line)[0] for line in lines),`` do not work?

**Comment by ppizarror** [comment]
You can also create a new PR :). A new widget requires a manager (for menu.add) and lots of new tests.

**Comment by vnmabus** [comment]
> What are you refering to get the right width? `max(self._font.size(line)[0] for line in lines),` do not work?

I meant that using `self._menu.get_width(inner=True)` overestimates the available space.

**Comment by vnmabus** [comment]
> You can also create a new PR :). A new widget requires a manager (for menu.add) and lots of new tests.

I think that at least multiline support could be added to the existing label widget.

**Comment by ppizarror** [comment]
> > What are you refering to get the right width? `max(self._font.size(line)[0] for line in lines),` do not work?
> 
> I meant that using `self._menu.get_width(inner=True)` overestimates the available space.

Got it! You can take a look at this example: https://github.com/ppizarror/pygame-menu/blob/685a2941bc940f0fad0d266700f95896ae50310a/pygame_menu/widgets/widget/textinput.py#L610-L629
Textinput also checks the available space of the menu (within its column). Maybe you could use some of these functions.

**Comment by vnmabus** [comment]
> I this case, `_get_max_container_width()` returns the max width of the column the widget resides.

Tried it, it still uses `menu.get_width(inner=True)` in my case, which is wrong.

**Comment by ppizarror** [comment]
Hi. I've implemented this feature. See #413 and let me know what you think :)

**Comment by ppizarror** [comment]
Usage: ``label = menu.add.label('lorem ipsum dolor sit amet this was very important nice a test is required', wordwrap=True)``

**Comment by ppizarror** [comment]
Today I uploaded v4.3.0 to PyPI which incorporates multiline labels. I'll close this issue by now. If anyone has more suggestions, please create a new issue 😄
