### ISSUE TITLE
Joystick support not working.

### ISSUE THREAD

**Issue by ffiarpg** [ppizarror/pygame-menu#414]
Has joystick support been tested recently? I've tried for a few hours to get it working or troubleshoot the issue without much luck. I tried the examples simple.py, multi_input.py, and game_selector.py

This script shows all inputs as working. I've tried two different controllers.
https://github.com/denilsonsa/pygame-joystick-test/blob/master/pygame-joystick-test.py

Would appreciate any help or suggestions.

**Comment by ppizarror** [comment]
I'll check your code with this menu. Joystick should be working, at least this is the first issue since 2020. Also our test pass, but who can't deny bugs ..

Thanks

**Comment by gustavklopp** [comment]
Are we supposed to be able to move up and down with the joystick pads (like using the arrow keys) right out of the box?
If that's so, I can confirm it's not working.

**Comment by ppizarror** [comment]
Hi, maybe this is related to #422, check out the new controller object in v4.3.0. I'll close this issue by now as I can't reproduce this bug, and our tests work.

Feel free to create any issue or PR. Greetings!
