### ISSUE TITLE
Image onselect does not work

### ISSUE THREAD

**Issue by enablex3** [ppizarror/pygame-menu#415]
Describe your environment information, such as:
- Windows & Linux
- python version: v3.9
- pygame version: v2.1.2
- pygame-menu version: v4.2.8

**Describe the bug**
When I click on the image I've added to my pygame menu, the function I've assigned to onselect does not get called

**To Reproduce**
`
def set_ship():
    global ship
    print("Clicked")

menu = pygame_menu.Menu('Main Menu', 500, 800, theme=pygame_menu.themes.THEME_DARK)

menu.add.selector('Difficulty: ', [('Easy', 1), ('Medium', 2), ('Hard', 3)], onchange=set_difficulty)
menu.add.selector('Music: ', [('ON', 1), ('OFF', 0)], onchange=set_music)
menu.add.selector('SFX: ', [('ON', 1), ('OFF', 0)], onchange=set_sfx)
menu.add.button('Play', play_game)
menu.add.button('Quit', pygame_menu.events.PYGAME_QUIT)

ships = settings["options"]["ships"]
menu.add.image(ships["The Goblin"]["original_img"], onselect=set_ship)

menu.mainloop(WIN)`

**Expected behavior**
The text "Clicked" is printed to the console

**Additional context**

**Comment by devfred78** [comment]
Hello,
Did you try to use the `selectable` parameter in the menu.add.image() method ?
In your example:
menu.add.image(ships["The Goblin"]["original_img"], onselect=set_ship, **selectable=True**).
I met the same issue, this parameter saved me :-) !

**Comment by enablex3** [comment]
This worked! Thank you!

**Comment by enablex3** [comment]
> Hello, Did you try to use the `selectable` parameter in the menu.add.image() method ? In your example: menu.add.image(ships["The Goblin"]["original_img"], onselect=set_ship, **selectable=True**). I met the same issue, this parameter saved me :-) !

This worked! Thank you! Thank you!

**Comment by enablex3** [comment]
Wow ! That worked! Thank you!
