### ISSUE TITLE
Run tests on Python 3.10

### ISSUE THREAD

**Issue by leestarb** [ppizarror/pygame-menu#419]
To ensure workability on it

**Comment by ppizarror** [comment]
Hi, I cannot manage to enable 3.10 tests because nosetest fails. Check it out: https://github.com/ppizarror/pygame-menu/runs/7719197346?check_suite_focus=true

**Comment by ppizarror** [comment]
Check out https://github.com/nose-devs/nose/issues/1122

**Comment by leestarb** [comment]
Ok. On my 3.10 machine the project working good

**Comment by leestarb** [comment]
Looks like the nose project is dead. I suggest forking it and fixing then

**Comment by ppizarror** [comment]
> Looks like the nose project is dead. I suggest forking it and fixing then

Thanks for your suggestion. Indeed ``nose`` is dead, so I upgraded all my repos to ``nose2`` which is -almost- the same. Greetings!
