### ISSUE TITLE
update_font() in ToggleSwitch does not update state_text_font_size

### ISSUE THREAD

**Issue by anetanel** [ppizarror/pygame-menu#420]
I hope I'm not missing something obvious..
I'm changing the size of the widget font when the size of the window changes, by calling update_font() for each widget in the menu.
It works well for all the widgets, except for the state text inside the toggle switch, which stays the same size it was initialized.
I could not find a function that updates the state text...

**Comment by ppizarror** [comment]
Fixed in #435. Thanks!
