### ISSUE TITLE
how to get the main menu object inside submenu?

### ISSUE THREAD

**Issue by MeldyTheCoder** [ppizarror/pygame-menu#423]
**Environment information**
Describe your environment information, such as:
- SO: win 10
- python version: v3.9
- pygame version: v2.1.2
- pygame-menu version: v4.2.8

I need to adjust the sound volume for all menus, including the main one. The volume settings menu is a child of the general settings, and the general settings menu is a child of the main menu. 

That is: Main Menu -> Settings Menu -> Volume Settings Menu. 

How do I apply the settings for the main menu from the child menu?

**Comment by ppizarror** [comment]
Hi, to set the souds please take a loot at https://pygame-menu.readthedocs.io/en/4.2.8/_source/add_sounds.html

In particular, you can add a custom function to "Volume Settings Menu". When creating the main menu, store that to a variable, therefore:

engine = sound.Sound()
engine.set_sound(sound.SOUND_TYPE_CLICK_MOUSE, '/home/me/click.ogg')
engine.set_sound(sound.SOUND_TYPE_OPEN_MENU, '/home/me/open.ogg')

menu = pygame_menu.Menu(...)
menu.set_sound(engine, recursive=True)  # Apply on menu and all sub-menus
def func(name):
    print('Hello world from', name)  # Name will be 'foo'

menu.add.button('Exec', func, 'foo',                   # Execute a function
                align=pygame_menu.locals.ALIGN_LEFT)
