### ISSUE TITLE
Touchscreen on PiTFT without mouse not working

### ISSUE THREAD

**Issue by asztalosdani** [ppizarror/pygame-menu#424]
**Environment information**
- OS: Raspbian 11 (bullseye)
- python version: v3.9.2
- pygame version: v1.9.6
- pygame-menu version: v4.2.8

**Describe the bug**
Running a menu with `mouse_visible=False` does not work on a Raspberry with a PiTFT touchscreen.

**To Reproduce**
I copied the menu from the [quickstart guide](https://pygame-menu.readthedocs.io/en/4.2.8/), and added `mouse_visible=False`.

**Expected behavior**
The menu does not react to any touch events.

**Additional context**
If I set `mouse_visible=True` it works as expected, but I want to disable the cursor. The mouse events are correctly triggered if I print them using
```py3
events = pygame.event.get()
for event in events:
    if event.type == pygame.QUIT:
        exit()
    if event.type == pygame.MOUSEMOTION:
        print(pygame.mouse.get_pos())
    if event.type == pygame.MOUSEBUTTONDOWN:
        print(pygame.mouse.get_pressed())
```
The `touchscreen` and `touchscreen_motion_selection` make no difference, but I'm not sure they should as they are only for pygame 2 right?

**Comment by ppizarror** [comment]
Hi! I'll take a look at this issue asap!

**Comment by ppizarror** [comment]
Does #427 solves your issue?

**Comment by ppizarror** [comment]
Nice. I'll publish v4.3.0 to pypi today
