### ISSUE TITLE
How to draw a background?

### ISSUE THREAD

**Issue by UltraRobot2017** [ppizarror/pygame-menu#432]
hello, I really liked your pygame_menu library. I'm a beginner and I'm trying to figure out your library. I want to create a menu and insert my image as a background on the entire screen so that this gray theme is not visible. I read your documentation and uploaded the image and then used the method .draw to which I transferred my screen, but still my image is not displayed on the screen. How do I display my background? It's also complicated by the fact that I don't know English well. Thank you in advance for the answer

[MENU_FINAL.zip](https://github.com/ppizarror/pygame-menu/files/10258702/MENU_FINAL.zip)

**Comment by ppizarror** [comment]
Hi 😃 , you can take a look at https://pygame-menu.readthedocs.io/en/4.3.1/_source/gallery.html, in particular:

https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/examples/other/image_background.py

**Comment by ppizarror** [comment]
Closed as finished
