### ISSUE TITLE
Adding frame to first column crashes when pack() is called.

### ISSUE THREAD

**Issue by bluefish2020** [ppizarror/pygame-menu#436]
**Environment information**
Describe your environment information, such as:
- SO: osx 12.6
- python version: v3.9.6
- pygame version: v2.1.2
- pygame-menu version: v4.3.2

**Describe the bug**
Creating a menu with 2 columns and adding a frame (v or h) throws a KeyError during frame.pack()

**To Reproduce**
Create a Menu with  columns=2, rows=1 then
    frame = menu.add.frame_h(width=250, height=100, border_width=3)
    label = menu.add.label('Col One')
    frame.pack(label)

[frame_crash.py.gz](https://github.com/ppizarror/pygame-menu/files/10302658/frame_crash.py.gz)

**Expected behavior**
Expected a two column menu with a frame on the left: 
![expected_2_column_menu_with_frame](https://user-images.githubusercontent.com/115673318/209528311-5ba4d8fe-d3d3-4fa3-80df-575673fd8928.png)

**Comment by ppizarror** [comment]
I'll release this critical issue in ``v4.3.3``. Already published to PyPI. Thanks!
