### ISSUE TITLE
Center menu items when scrollbar is shown

### ISSUE THREAD

**Issue by asztalosdani** [ppizarror/pygame-menu#446]
**Environment information**
Describe your environment information, such as:
- OS: win/linux
- python version: v3.9
- pygame version: v1.9.6
- pygame-menu version: v4.3.1

**Describe the bug**
I would like to center the menu items even when there is a scrollbar. (I added the red line in paint to visualize the center)
![image](https://user-images.githubusercontent.com/9664767/218218397-514de10c-05fb-41c7-8762-1bcae17fa688.png)

**To Reproduce**
```py3
import pygame_menu
from pygame_menu.examples import create_example_window


surface = create_example_window('Example - Simple', (320, 240))

menu = pygame_menu.Menu(height=240, theme=pygame_menu.themes.THEME_BLUE, title='Main menu', width=320)

menu.add.button('Option1')
menu.add.button('Option2')
menu.add.button('Option3')
menu.add.button('Option4')
menu.add.button('Option5')
menu.add.button('Quit', pygame_menu.events.EXIT)

if __name__ == '__main__':
    menu.mainloop(surface)
```

**Expected behavior**
Center the items, or at least give me an option to toggle this behaviour.

**Additional context**
The reason is, I'm creating an application to be run on a Raspberry Pi on a 320x240 tft screen, with a few physical buttons below it, so you clearly see where is the center of the screen, and that the menu items are off-center. But even if you don't have a tiny screen, if you have a main menu with a few items, so without a scrollbar -> centered, then a submenu with more items so with a scrollbar -> off-center, and you switch between them, the jump is noticable.

**Comment by ppizarror** [comment]
I think theme should receive a parameter named center_ignore_scrollbar_thickness. The problem here is that when computing the position, if the menu overflows, then the thickness of the scrollbars is added. Hence, the widgets are centered concerning their scrollarea, but not regarding the window. This value must be ``False`` for backward-compatibility reasons.

**Comment by asztalosdani** [comment]
Yes, that should do it!

**Comment by ppizarror** [comment]
Fixed in #449. Let me know if this solves your issue 👯

**Comment by asztalosdani** [comment]
Yes, it works, thanks!

**Comment by ppizarror** [comment]
Version ``v4.3.7`` uploaded to pip!
