### ISSUE TITLE
Python version limit

### ISSUE THREAD

**Issue by leestarb** [ppizarror/pygame-menu#450]
Hello. I see the minimum version required for this package is Python 3.7.

However pygame also supports Python 3.6.
I want to use it with pygame-menu, but it does not support 3.6 version.

So please, do something to bring Python 3.6 support.

I really like your package and always use it with my projects!

**Comment by ppizarror** [comment]
Python 3.6 compatibility is now added in the new ``v4.3.8`` 🎉. See https://pypi.org/project/pygame-menu/.
Greetings,

**Comment by leestarb** [comment]
Thanks a lot!
