### ISSUE TITLE
Resize all submenus

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#453]
**Environment information**

- OS: Mac OSX
- python version: v3.7
- pygame version: v2.x
- pygame-menu version: v4.3.8

**Describe the bug**
When resizing menu using `menu.resize(width, height)`, submenu are not resized.

**Expected behavior**
Is there any easy method to pass new size to all submenus?

**Comment by ppizarror** [comment]
Hello, @anxuae. I've added ``recursive`` parameter to the ``resize`` method in #454. Let me know if that solves your issue.

**Comment by anxuae** [comment]
Hi @ppizarror 

Thanks a lot for the quick fix, it's working perfectly!
pygame-menu is really a wonderfull project 😃

**Comment by ppizarror** [comment]
Super. I'll merge and upload to PyPI right now. Greetings!!
