### ISSUE TITLE
Unable to hide the cursor, due to pygame_menu

### ISSUE THREAD

**Issue by UltraRobot2017** [ppizarror/pygame-menu#455]
- OS: win
- python version: v3.11.1
- pygame version: v2.1.3 dev8
- pygame-menu version: v4.3.1

Due to the use of pygame_menu, pygame.mouse.set_visible() does not work

```
import sys, pygame, pygame_menu
pygame.init()

screen = pygame.display.set_mode((1920, 1080), pygame.FULLSCREEN)
pygame.mouse.set_visible(False)

menu = pygame_menu.Menu('Bug', 1920, 1080)
pygame.mouse.set_visible()

while True:
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    key = pygame.key.get_pressed()

    if key[pygame.K_ESCAPE]:
        pygame.quit()
        sys.exit()

    menu.draw(screen)
    menu.update(events)
    pygame.display.update()
```

The cursor should have disappeared, but it still remains visible, everything works without pygame_menu

**Comment by ppizarror** [comment]
Hi! Right now, the ``Menu`` updates the cursor visibility. Thus, I introduced a new param ``mouse_visible_update`` to disable this feature.

Can you test #456, using ``menu = pygame_menu.Menu('Bug', 1920, 1080, mouse_visible_update=False)``, to test this feature?

**Comment by UltraRobot2017** [comment]
So quickly answered, thanks a lot, everything works)

**Comment by ppizarror** [comment]
I'll merge and upload to PyPI once #453 is solved; greetings 😄
