### ISSUE TITLE
Assert bgfun as callable rather than types.FunctionType types.MethodType

### ISSUE THREAD

**Issue by jwllee** [ppizarror/pygame-menu#47]
### Problem
Currently, ```Menu``` class requires ```bgfun``` to be either ```types.FunctionType``` or  ```types.MethodType``` if ```dopause``` is ```True```. This excludes other callables, e.g., [```partial```](https://docs.python.org/3.7/library/functools.html#functools.partial) from ```functools```. 

Also, it seems that the code only requires ```bgfun``` to be callable.

### Proposed solution:
Why don't we just make the assertion as callable is ```True```?

### Reason:
Things like partial is useful if I were to have a bgfun that can accept a surface as a parameter rather than having it as a global variable.

**Comment by jwllee** [comment]
I would be happy to do a pull request if the issue gets an ok :)

**Comment by ppizarror** [comment]
Feel free to create any pull request 😄
