### ISSUE TITLE
Have a _sdl2 mode where make_surface is never called whith alpha=True

### ISSUE THREAD

**Issue by cbdj** [ppizarror/pygame-menu#470]
**Is your feature request related to a problem? Please describe.**
When using pygame-menu(-ce) in sdl2 mode, we get exceptions each time make_surface is called with alpha=True :

No video mode has been set
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame_menu\utils.py", line 434, in make_surface
    surface = pygame.Surface.convert_alpha(surface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Describe the solution you'd like**
convert_alpha should no more be called as it no longer provide much improvement in normal mode, and breaks sdl2 mode.

**Describe alternatives you've considered**
Or there should be a sdl2 mode...

**Comment by ppizarror** [comment]
(After more than a year a half) I added ``ut.configure_alpha(state)`` to disable/enable surface alpha. Usage mode:

```python
import pygame_menu
import pygame_menu.utils as ut
...
ut.configure_alpha(False)
...
menu = pygame_menu.Menu(
    height=300,
    theme=pygame_menu.themes.THEME_BLUE,
    title='Welcome',
    width=400
)
```
