### ISSUE TITLE
bug in windows

### ISSUE THREAD

**Issue by andrew-karppinen** [ppizarror/pygame-menu#479]
![Sieppaa](https://github.com/ppizarror/pygame-menu/assets/99529988/a8eedf07-dd28-4858-a7c4-c8bd51810738)
**Environment information**
Describe your environment information, such as:

- OS: windows
- python version: v3.x
- pygame version: v2.x
- pygame-menu version: v3.x.x

Window opens so that it's pinned to the top-left corner and there's no title bar.
There's no bug on Linux, but I often encounter it on Windows.

**Comment by ppizarror** [comment]
Hi, can you provide a minimal test case, or show the code around how you manage window, the menu creation, and so on? thanks

**Comment by andrew-karppinen** [comment]
The problem was actually just my own incorrect way of measuring the screen resolution, the "problem" is not related to the pygame menu library, but rather to pygame in general. Here is the sample code, and if you delete that line, there is no problem.



`import pygame
import pygame_menu



pygame.init()


resolution = pygame.display.set_mode().get_size() #get screen resolution



surface = pygame.display.set_mode((600, 400), pygame.WINDOWMOVED)





menu = pygame_menu.Menu('Welcome', 400, 300,
                       theme=pygame_menu.themes.THEME_BLUE)

menu.add.text_input('Test :', default='')
menu.add.selector('Difficulty :', [('Hard', 1), ('Easy', 2)])



menu.mainloop(surface)`
