### ISSUE TITLE
Runs extremely slowly on older hardware. How to disable transition / fade effects?

### ISSUE THREAD

**Issue by joncox123** [ppizarror/pygame-menu#484]
I find pygame-menu runs extremely slowly on older hardware due to the blur / fade / transition effects. How can I turn off all unnecessary updates and effects? I want the bare minimum, which is a direct update of the menu screen when an event occurs.

It seems that pygame menu always implements a fade out or transparency transition effect. Perhaps it does this by storing a list of previously rendered surfaces and blitting the old surfaces with transparency (alpha) to create a kind of "slow response" effect.

Unfortunately, this practice is unnecessary and extremely slow on hardware without transparency acceleration. 

How can I disable this? It wasn't clear from searching the code.

**Comment by ppizarror** [comment]
(After more than a year and a half) I added ``ut.configure_alpha(state)`` to disable/enable surface alpha on the new ``v4.5.1``. Usage mode. This should enhance performance.

This comment should be used as a future reference. Thanks!

```python
import pygame_menu
import pygame_menu.utils as ut
...
ut.configure_alpha(False)
...
menu = pygame_menu.Menu(
    height=300,
    theme=pygame_menu.themes.THEME_BLUE,
    title='Welcome',
    width=400
)
```
