### ISSUE TITLE
Controlling selection from outside

### ISSUE THREAD

**Issue by AndreasPantle** [ppizarror/pygame-menu#489]
I have a special question (but I need to say that I'm new to pygame-menu). I discovered it today and it feels like this is solving some of my use cases so far. 

I have some rotary encoders connected via CAN. There is a thread which are getting the CAN frames from the encoders and put it onto a Python Queue (this is working and existing). 

So far I need to control the menu from the code itself. Is this possible?  
Say for example: I'm on a loop and waiting for an incoming Queue event -> The encoder is incrementing and now I'll see it in an incoming object from the Queue. How can I move the selection in the menu?

**Comment by AndreasPantle** [comment]
Actually the controlling (move menu cursor down) of the menu with:

``` python
key_event = pygame.event.Event(
    pygame.locals.KEYUP,
    key=pygame.locals.K_DOWN,
    mod=pygame.locals.KMOD_NONE,
    unicode='',
    repeat=0
)

# Post the event to the event queue
pygame.event.post(key_event)
```

Is not possible. Can someone confirm that?

**Comment by AndreasPantle** [comment]
The issue is solved with: `keyboard_ignore_nonphysical=False`...!

**Comment by ppizarror** [comment]
Great discovery. Hope this will help future folks. Greetings,

Pablo
