### ISSUE TITLE
Gamepad/joystick support

### ISSUE THREAD

**Issue by ironsmile** [ppizarror/pygame-menu#6]
Hello! I am experimenting with using your menu library in a [small project](https://github.com/ironsmile/tank4eta) of mine. I really want to have full gamepad support throughout the game and I am willing to add it to your library. Would you be interested in such a pull request?

**Comment by ppizarror** [comment]
Yes sure! Even your game seems pretty fun to play and code, i will take a look too, maybe a map editor would be perfect

**Comment by ironsmile** [comment]
Great! I will send you the PR when I have something working.

**Comment by ppizarror** [comment]
Version updated, thanks!
