### ISSUE TITLE
Can not post key event to handle menu

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#67]
Can you tell me what the objective of the function `_check_key_pressed_valid()` in `Menu` class?

I'm currently developing on a raspberry-pi and I'm trying to handle menu using physical buttons. When a physical button is pressed, I post the event `pygame.event.Event(pygame.KEYDOWN, key=pygame.K_DOWN)` , however the function `_check_key_pressed_valid()` discard it.

**Comment by ppizarror** [comment]
Sometimes the key events does not correspond to the keyboard events, so I added the method check_key that verify KEYDOWN is valid. For testing purposes you can raise an KEYDOWN event by adding 'test' to the dict:

`pygame.event.Event(pygame.KEYDOWN, {"key"=pygame.K_DOWN, "test"=true})`

See also: https://github.com/ppizarror/pygame-menu/blob/1e40ec70512544e38f7b4a45b5e99f6a89406fb5/test/_utils.py#L142

**Comment by ppizarror** [comment]
In some cases if you press a key too fast and release it the event state of pygame stills recognizes the last pressed key as pressed (the KEYUP is ignored). That bug was very common in TextInput widget

**Comment by ppizarror** [comment]
If you want we can rename 'test' to another-more clear name

**Comment by anxuae** [comment]
Ok for me, I understand now the reason. I will use the key `test` for my custom event.
The name is ok, see in your test why you call it like that.

Thanks
