### ISSUE TITLE
Controls UP and DOWN are inverted

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#68]
Is it normal that the UP and DOWN controls are inverted?
https://github.com/ppizarror/pygame-menu/blob/1e40ec70512544e38f7b4a45b5e99f6a89406fb5/pygameMenu/controls.py#L53-L54

https://github.com/ppizarror/pygame-menu/blob/1e40ec70512544e38f7b4a45b5e99f6a89406fb5/pygameMenu/menu.py#L817-L821

**Comment by ppizarror** [comment]
I know it's kinda confusing, but `KEY_MOVE_DOWN` refers to "go down into the menu options", not the down key, I'm opened to any suggestions

**Comment by anxuae** [comment]
Ok like in on smartphone, gesture is inverted.
Down is related to the widget add order.

**Comment by ppizarror** [comment]
We will change this behaviour? If not I'll close this issue 🤔

**Comment by anxuae** [comment]
I close it, I have no better naming than you
