### ISSUE TITLE
Unable to transition screen more than once

### ISSUE THREAD

**Issue by skmatz** [ppizarror/pygame-menu#71]
I want to implement 3 menu screen transitions with the following code.

```python
menu3 = MenuTemplate(surface=SURFACE, title="manu3")
menu3.add_option("back", pygameMenu.events.BACK)

menu2 = MenuTemplate(surface=SURFACE, title="manu2")
menu2.add_option("go to menu3", menu3)

menu1 = MenuTemplate(surface=SURFACE, title="manu1")
menu1.add_option("go to menu2", menu2)

clock = pygame.time.Clock()
while True:
    clock.tick(60)
    menu1.mainloop()
```

`MenuTemplate` is an inherited class of `pygameMenu.Menu`.

I expect following screen transitions:

```
menu1 -> menu2 -> menu3
```

In practice, however, only the transition from menu1 to menu2 works and cannot transition from menu2 to menu3.

Is this the intended behavior? Or is it a bug?

**Comment by ppizarror** [comment]
It's a bug, I think I've fixed this. Can you test the new menu.py file?

**Comment by ppizarror** [comment]
![example](https://user-images.githubusercontent.com/12925256/62674573-f8040700-b970-11e9-8a30-277c403c8808.gif)
I've updated the example too (examples/game_selector.py)

**Comment by skmatz** [comment]
Thanks!
It works I intended!

**Comment by ppizarror** [comment]
I'll post this patch (2.0.3) to PyPi. Let me know if you find any other bug related to menu open/back events 😄
