### ISSUE TITLE
AssertionError: Bgfun must be a function (or None if menu does not pause execution of the application)

### ISSUE THREAD

**Issue by anustupdas** [ppizarror/pygame-menu#73]
Hi

I am trying to create a simple menu on my display surface but keep on getting this error.

AssertionError: Bgfun must be a function (or None if menu does not pause execution of the application)

Here is my code.

import pygameMenu

import math, random, sys
import pygame
from pygame.locals import *

# exit the program
def events():
    for event in pygame.event.get():
        if event.type == QUIT or (event.type == KEYDOWN and event.key == K_ESCAPE):
            pygame.quit()
            sys.exit()

# initialise display
pygame.init()
CLOCK = pygame.time.Clock()
DS = pygame.display.set_mode((900, 700))
pygame.display.set_caption("code.Pylet - Scrolling Background with Player")
FPS = 500

# define some colors
BLACK = (0, 0, 0, 255)
WHITE = (255, 255, 255, 255)

bg = pygame.image.load("bg1.jpg").convert()

def fun():
    pass

# main loop
while True:
    events()
    help_menu = pygameMenu.Menu(DS, 200, 300, font='Arial', title='kak')

    # help_menu = pygameMenu.TextMenu(surface, window...)
    help_menu.add_option('Simple button', fun, align=pygameMenu.locals.ALIGN_LEFT)
    #help_menu.add_option('Return to Menu', pygameMenu.events.MENU_BACK)

    DS.blit(bg, (0, 0))

    pygame.display.update()
    CLOCK.tick(FPS)
    DS.fill(BLACK)

Why is this happening?

**Comment by anustupdas** [comment]
I figured it out.... Thanks...

**Comment by ppizarror** [comment]
Hi, If you tell me what was your error I can improve the documentation

**Comment by anustupdas** [comment]
Hi,
 First of all I was declaring the menu within the While loop...

Secondly while declaring the menu i did not include the bgfun parameter as it was not mentioned.
Then I understood that I have to include the bgfun parameter and has to pass a function for that parameter.

Thanks and Regards,
Anustup.
