### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by FreeMotion45** [ppizarror/pygame-menu#74]
Would be cool if you could replace a button text with an image of your own.

**Comment by ppizarror** [comment]
If anyone is interested in this feature, file https://github.com/ppizarror/pygame-menu/blob/217ee799f2f5a43db406eb46b4252b7be7d0edf8/pygameMenu/widgets/widget.py#L275 must be overwritten. By now all widgets are rendered using "render_string" method that actually creates a surface containing ONLY the text inside the widget. If you want to use an image as a background first you must create a surface, then paste the image into the surface, and then render a string text into the surface.

I suggest something like:
`add_option(text, background=image)` this background image could be used by the renderer as a starting point to create the text

**Comment by ppizarror** [comment]
This can be added as a new widget

**Comment by ppizarror** [comment]
Created new Image widget
