### ISSUE TITLE
OnReturn doesn't work with joystick input

### ISSUE THREAD

**Issue by YoshiFan501** [ppizarror/pygame-menu#76]
I am making a menu that can work with a controller, and navigating the menus works fine, but when i make selection switches that use onreturn instead of onchange, nothing happens. they work when i hit enter on the keyboard, but not the A button on my controller.

**Comment by ppizarror** [comment]
Hi! I think I fixed this issue. Please see #77 
If it works could you see if other widgets are functioning properly?

Thanks!

**Comment by ppizarror** [comment]
Related #78
