### ISSUE TITLE
Adding "input text" option?

### ISSUE THREAD

**Issue by ppizarror** [ppizarror/pygame-menu#8]
A input text option to menu would be nice, but i don't know how to gather all keyboard events without "event crash" with the main menu, maybe using a inner mainloop to gather events should work.

**Comment by anxuae** [comment]
Hi

Yes it would be really cool to have a `TextInput` class 😄. Looking in examples using libraries like `pug` or `EzText`, I think that you will have no other choice that include an inner events loop.

anxuae

**Comment by ppizarror** [comment]
I found a pygame project that could be useful: https://github.com/Nearoo/pygame-text-input

**Comment by anxuae** [comment]
Hi,

I'm currently working on this issue. If you are ok, this could be part of the 2.0 release.
However, this may impact a large part of project because the way to update the ``pygame-text-input`` is radically different from the one of a ``selector`` for instance.

I think  it could be a good idea to make a ``widget`` package and move ``selector`` and ``textinput`` inside. It will be inline with proposal #18 .

Anxuae

**Comment by anxuae** [comment]
You can have a look to my proposal here: https://github.com/anxuae/pygame-menu/tree/text-input
Any feedback is welcome!

**Comment by ppizarror** [comment]
> Hi,
> 
> I'm currently working on this issue. If you are ok, this could be part of the 2.0 release.
> However, this may impact a large part of project because the way to update the `pygame-text-input` is radically different from the one of a `selector` for instance.
> 
> I think it could be a good idea to make a `widget` package and move `selector` and `textinput` inside. It will be inline with proposal #18 .
> 
> anxuae

it's an amazing addition to pygame-menu, once you finish I'll push the new version to pypi.

**Comment by ppizarror** [comment]
> You can have a look to my proposal here: https://github.com/anxuae/pygame-menu/tree/text-input
> Any feedback is welcome!

My feedback:
1. I think you should disable backspace button (back event) when the user is typing something. Backspace should delete text.
2. The length of the widget should not exceed the menu width. If the text is greater than some value (like 40) or the widget width is greater than the menu some "word ellipsis" should appear.
3. When I enter to the menu, some events are provided to the widget. Maybe adding a minimal time should be added to the input, for example, 100ms, if the user writes anything in less than 100ms (or the user press enter button?) the input text must ignore all of that input. That prevents errors if the user is navigating too quickly within the menu.

Feel free to PR

**Comment by ppizarror** [comment]
@anxuae `self._cursor_surface` should be calculated using widget real size font instead of self._font_size I guess, noticed this using some new fonts I added (helvetica for instance), there you can see that the cursor is way bigger than the widget

**Comment by ppizarror** [comment]
Also, some keys dont work well so I disabled them, like `_pygame.K_NUMLOCK, _pygame.K_TAB, _pygame.K_CAPSLOCK`. I don't know why if you press NUMLOCK, TAB or CAPSLOCK the event loop goes crazy, so I disabled them. Capslock still works (Verified with Helvetica font)

**Comment by anxuae** [comment]
> @anxuae `self._cursor_surface` should be calculated using widget real size font instead of self._font_size I guess, noticed this using some new fonts I added (helvetica for instance), there you can see that the cursor is way bigger than the widget

Exact, see my PR

**Comment by ppizarror** [comment]
@anxuae I've added `type_data` optional argument, now text input only can contain INT/FLOAT/STRING, updated example 3 showing the new features

**Comment by anxuae** [comment]
Good idea. I will call it rather ``input_type`` to be consistent with the name of the widget.

I think that the ``try...except...`` in the ``get_value`` are not necessary has the inputs are already checked when entered.

**Comment by ppizarror** [comment]
> Good idea. I would call it rather `input_type` to be consistent with the name of the widget.
> 
> I think that the `try...except...` in the `get_value()` method are not necessary has the inputs are already checked when entered.

`input_type` I agree, I'll change that.
The `try...except...` is used to change the data type of the value (because it's a string...)

```
# If data is valid
if data_valid:
      self._input_string = str(new_string)

      lkey = len(event.unicode)
```

So any error could occur when casting from string to int/float (I think...)

**Comment by anxuae** [comment]
@ppizarror sorry I made wrong action on my repo, I lost the PR about shadow rendering. I hope you have still the code on your local repo. Else I will redo the job.

Sorry again.

**Comment by ppizarror** [comment]
> @ppizarror sorry I made wrong action on my repo, I lost the PR about shadow rendering. I hope you have still the code on your local repo. Else I will redo the job.
> 
> Sorry again.

What happened? 🤔 I never have lost any branch or repo, Did you deleted .git/index?
I pushed all the commits I and you did from pr/40 😄, so what you think about reusing surfaces? (See my last comments on https://github.com/ppizarror/pygame-menu/pull/40

**Comment by anxuae** [comment]
Ouf, nothing is lost!  My first error was to make a PR on my master branch, my second was to update my master with your changes to test them, and force-push on my fork, which lead to the deletion on my PR.

I made a simple test about reuse of surface in example 3:

```
import timeit
print(timeit.timeit(stmt='wid1.render_string("This is a text", (0, 20, 50))',
              setup="from __main__ import wid1", number=100000))
```

without reuse:
```
0.977579s
```
with reuse:
```
0.056215s
```

**Comment by ppizarror** [comment]
Wow, never expected x17 time reducton, amazing. I'll search for other things we could save time

**Comment by ppizarror** [comment]
> Ouf, nothing is lost! My first error was to make a PR on my master branch, my second was to update my master with your changes to test them, and force-push on my fork, which lead to the deletion on my PR.
> 
> I made a simple test about reuse of surface in example 3:
> 
> ```
> import timeit
> print(timeit.timeit(stmt='wid1.render_string("This is a text", (0, 20, 50))',
>               setup="from __main__ import wid1", number=100000))
> ```
> 
> without reuse, for 100000 calls to `render_string()`:
> 
> ```
> 0.977579s
> ```
> 
> with reuse, for 100000 calls to `render_string()`:
> 
> ```
> 0.056215s
> ```
> 
> This is 17 times faster. This could be good improvement, but don't know if my solution is the best.

Also tested:
```
print(timeit.timeit(stmt='main_menu.draw()',
                    setup="from __main__ import main_menu, pygame", number=10000))
```
In my computer time decreased from 3.6 seconds to 1.93 seconds (50% time reduction).

I created `apply_font` widget method, there some calculations could be done each time a new font is applied, for example label size in selector, ellipsis size in textinput, etc. That method must be overrode, or not? What you think 🤔 

I looked for some other things to improve and found some:
- `TextInput.text_input` draw method recalculates cursor position each time, adding some kind of "cache" could save us some time
- The line `rect.inflate(16, 4)` in Menu.draw() could be cached too (I think...)

Solving this I'll push the v2.0.0 version today (Monday), let me know if there's another thing you want to review

**Comment by anxuae** [comment]
> I created `apply_font` widget method, there some calculations could be done each time a new font is applied, for example label size in selector, ellipsis size in textinput, etc. That method must be overrode, or not? What you think thinking

I think this method should be private, maybe better if must be overridden (all widgets will have font, I think).

>     * `TextInput.text_input` draw method recalculates cursor position each time, adding some kind of "cache" could save us some time

Yes, we can have a flag ``_cursor_updated`` set to ``True`` in the ``update()`` method when cursor position has been updated. The cursor shall be rendered only when this flag is ``True``, then set it to ``False``.
Also I think that cursor shall be rendered in the ``_render()`` method and blit on the internal surface (``_surface``), not direcly on the surface given to the ``draw()`` method.

>     * The line `rect.inflate(16, 4)` in Menu.draw() could be cached too (I think...)

Yes, also, it could be done in the draw method of the widget: there is the flag ``selected`` which permits to know if the outer rect shall be drawn.

**Comment by ppizarror** [comment]
Issue closed
