### ISSUE TITLE
menu_color  can set  transparency color？

### ISSUE THREAD

**Issue by jarwin123** [ppizarror/pygame-menu#80]
hi all:
    have some method set menu_color   transparency color ?    i  try color tuple  (0,0,0,0) ,but it not effect?

**Comment by ppizarror** [comment]
Check `menu_alpha` parameter. Does that solve your issue?

**Comment by jarwin123** [comment]
yes，solved .thank you ！！
play_menu.add_option('Start', fun, align=pygameMenu.locals.ALIGN_LEFT, text_fontsize=10)
why text_fontsize is cannot change?

**Comment by ppizarror** [comment]
Add option does not have text_fontize. Check font_size parameter of Menu constructor.  Anyway I'll push a new PR that addds font_size as optional parameter to add_* methods

**Comment by ppizarror** [comment]
Check out new version 2.1.0 😄
