### ISSUE TITLE
Run without soundcard

### ISSUE THREAD

**Issue by ArturN-MS** [ppizarror/pygame-menu#82]
> Traceback (most recent call last):
>   File "game_selector.py", line 333, in <module>
>     main()
>   File "game_selector.py", line 221, in main
>     window_width=WINDOW_SIZE[0]
>   File "/usr/local/lib/python3.7/dist-packages/pygameMenu/menu.py", line 252, in __init__
>     self._sounds = _Sound()
>   File "/usr/local/lib/python3.7/dist-packages/pygameMenu/sound.py", line 132, in __init__
>     buffer=buffer)
> pygame.error: No available audio device

It will be possible to run this library without sound card?

**Comment by ppizarror** [comment]
Oops. Never considered this case. I'll fix this issue today

**Comment by ppizarror** [comment]
I think I've fixed this issue #83, I'll release a new version right now

**Comment by ppizarror** [comment]
v2.1.2 has been uploaded, please update via pip and let me know if the bug has been fixed 😄

**Comment by ArturN-MS** [comment]
It's works. Thank you :)
