### ISSUE TITLE
Is there a way remove an option from a menu?

### ISSUE THREAD

**Issue by ArslanAftab** [ppizarror/pygame-menu#84]
Hey ppizarror, I've been working with your library for a bit now and was wondering if there is a way to remove certain options from a menu. i.e. remove the option "A" once a condition has been met. 

I have experimented with menu.clear() followed by menu.add_option("text", menu_name) and so forth but it gives me a "list out of index error" this does indeed let me update the options but they appear in a weird location and cause a runtime error. 

Just to give some context, I have made a login menu that logs the user in. Once the user is successfully logged in it returns them to the main menu, but I want to make the option for the login menu to disappear immediately after this.

This is the initial main menu:
![image](https://user-images.githubusercontent.com/57289789/74477215-c7ae9f80-4ea2-11ea-8961-d97048909159.png)

And this is what it looks like after logging in:
![image](https://user-images.githubusercontent.com/57289789/74477302-f9276b00-4ea2-11ea-9e27-e3a041f26919.png)

I'd love any support and or general guidance. Thanks in advance

**Comment by ppizarror** [comment]
Currently the library does not support any method to delete the items (options) but it's really easy to do, maybe in the following weeks I'll create that behaviour. 

An idea: add option method returns an "Widget" object. That class could have a "delete" method, that removes the object from the parent Menu, and declares the status of the Items S "deleted/removed". Something like

`
a = menu.add_option(....)
...
a.delete()
`
Another idea is to provide a "delete" method for the menu class, only items that has an id could be deleted.

`
menu.add_option(..., I'd="hi")
...
menu.delete(id="hi")
`

:thinking:

**Comment by ppizarror** [comment]
Reopening, this must feature must be added

**Comment by ppizarror** [comment]
I'll work on this!

**Comment by ppizarror** [comment]
#172

**Comment by ppizarror** [comment]
Merged and added to the menu!
