### ISSUE TITLE
Support Chinese characters?

### ISSUE THREAD

**Issue by wplbyx** [ppizarror/pygame-menu#85]
I tried to display Chinese characters, but they didn't display properly. Does it support Chinese characters, or does it mean configuring something? Thanks.

**Comment by ppizarror** [comment]
Does the font you use support Chinese characters? By default I don't
provide any Chinese font file, if you wish you could send me an open source
font file (ttf file) to test and add to the library. I think that pygame
supports that characters without problems.

**Comment by wplbyx** [comment]
Okay, thank you for your reply.

**Comment by ppizarror** [comment]
> Okay, thank you for your reply.

My email is in my profile. After some tests I'll look for some changes to be made on the library to fully support Chinese and other non ASCII chars.
Greetings

**Comment by wplbyx** [comment]
This can display Chinese characters. I use the system font with Chinese characters to display them normally. You said that you can use ttf to expand the font, I went to the system to find a font library with Chinese, and tried it and found that it can display normally! thank you very much.
