### ISSUE TITLE
Joystick initialization issue

### ISSUE THREAD

**Issue by arpruss** [ppizarror/pygame-menu#86]
pygame docs say that pygame.joystick.init() is automatically called by pygame.init(). This means that in the Menu constructor, pygame.joystick.get_init() can return true and hence no joysticks get supported. I suggest changing the relevant code to:
```
        self._joystick = joystick_enabled
        if self._joystick:
            if not _pygame.joystick.get_init():
                _pygame.joystick.init()
            for i in range(_pygame.joystick.get_count()):
                _pygame.joystick.Joystick(i).init()
```

**Comment by ppizarror** [comment]
thanks, fixed! new version'll be released today
