### ISSUE TITLE
Color input widget

### ISSUE THREAD

**Issue by anxuae** [ppizarror/pygame-menu#87]
As discussed in the [pibooth#128](https://github.com/werdeil/pibooth/issues/128), it could be useful to have a widget used to pickup colors.

**Comment by ppizarror** [comment]
So this is the basic prototype we have right now?

![image](https://user-images.githubusercontent.com/12925256/77362492-c4bf8e00-6d2f-11ea-933a-cbccde5fb164.png)

**Comment by anxuae** [comment]
Yes this is the prototype.

**Comment by ppizarror** [comment]
PR: #94

**Comment by ppizarror** [comment]
@anxuae somehow we need to use "3 instances" of textinput for this widget. Re-coding an input for each channel (r,g,b) is quite difficult. The only problem here is that the 3 instances should exist in the same <surface>, also mouse support should be added (click one line of text should change the default active input).

Each instance of textinput only can receive numbers from 0 to 255. After each change .on_change() method sould call the previewer to create a surface with the desired background color.

Another solution, **way more easier** is to create the widget based on textinput. But in this case the user must write the color in terms of "R,G,B" like:

Color:  34, 4, 34

Obiously, delete event will be controlled by the application. If the cursor is at position X, but in the string [X-1] there's a comma then delete is disabled. So the user only can delete the number between the "commas". Copy, paste, also selection could be disabled for this widget.

Also this widget can have a parameter "type", I suggest "rgb" and "hex". Hex is quite the same, but only colors like "#ff0000" are valid.

Let me know what you think 🤔

**Comment by anxuae** [comment]
> Another solution, way more easier is to create the widget based on textinput. But in this case the user must write the color in terms of "R,G,B" like:
>Color: 34, 4, 34

That's fine for me. Maybe use the `-` or `|` char instead of comma, this is much more pretty .

>Obviously, delete event will be controlled by the application. If the cursor is at position X, but in the string [X-1] there's a comma then delete is disabled. So the user only can delete the number between the "commas". Copy, paste, also selection could be disabled for this widget.

In fact the separator character could be added and deleted automatically when typing. Ling widget used to enter a date which automatically add a `/` between day, month and year.
The separator is deleted when too few numbers are entered.
In this case the widget can be a similar to a text input accessing only 9 digits.

e.g. sequence to type the RGB color 129/248/33 will be (dash and spaces added automatically by the widget):
```
12
123 - 
123 - 2
123 - 248 -
123 - 248 - 33
```

> Also this widget can have a parameter "type", I suggest "rgb" and "hex". Hex is quite the same, but only colors like "#ff0000" are valid.

I agree

**Comment by ppizarror** [comment]
PR: #100

**Comment by ppizarror** [comment]
Merged. Added support for HEX and RGB. onreturn, onchange should work too. Added tests, get_value, set_value, clear. I don't know what else I'm missing.

This should be shipped with version 2.2 🤔
