### ISSUE TITLE
Put an image as Background

### ISSUE THREAD

**Issue by AlvaroN1997** [ppizarror/pygame-menu#9]
Hi! this library helped me a lot seriously, but i want to know something for my project, if there is one way to put a image as background on the menu, i would help me a lot.
Thank you very much!

**Comment by ppizarror** [comment]
Hi!

Yes, you can define a "bgfun" function that is called on menu rendering: https://github.com/ppizarror/pygame-menu#creating-menus

You can see an example of this:
https://github.com/ppizarror/pygame-menu/blob/master/example.py Line 68

There's a background function that blits a color on the surface. it's used as bgfun on main menu object (line 168).

If you want an image as background simple redefine that function:

```python
background_image = pygame.image.load(".../background.png")

def mainmenu_background():
    """
    Background color of the main menu, on this function user can plot
    images, play sounds, etc.
    """
    surface.blit(background_image, (0, 0)) #example, just place the image anywhere you want

```
Greetings from Chile.

**Comment by ppizarror** [comment]
Issue closed
